### ISSUE TITLE
Error when trying to run legacy/train.py

### ISSUE THREAD

**Issue by petertennis** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#106]
Hi 
I am running 
python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

After a bunch of warnings, I get 

Traceback (most recent call last):
  File "legacy/train.py", line 184, in <module>
    tf.app.run()
  File "C:\Anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 300, in train
    train_config.optimizer)
  File "C:\tensorflow1\models\research\object_detection\builders\optimizer_builder.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "C:\tensorflow1\models\research\object_detection\builders\optimizer_builder.py", line 112, in _create_learning_rate
    learning_rate_sequence, config.warmup)
  File "C:\tensorflow1\models\research\object_detection\utils\learning_schedules.py", line 160, in manual_stepping
    raise ValueError('First step cannot be zero.')
ValueError: First step cannot be zero.

Any suggestions appreciated. Also, is the recommendation still to use train.py or is it really deprecated now in favor of just using model_main.py. See another post around why I am struggling with that approach also.

**Comment by smugamerican** [comment]
I think this was already solved here: https://github.com/tensorflow/models/issues/3794

**Comment by petertennis** [comment]
Yes indeed - very much appreciated
