### ISSUE TITLE
'utf-8' problem! plz help me!

### ISSUE THREAD

**Issue by gktjsdldi** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#110]
Hi! Thank you for your efforts. 
I'm having a problem when using train.py. The output is below-

(tensorflow) C:\Anaconda3\envs\tensorflow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    tf.app.run()
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\Anaconda3\envs\tensorflow\models\research\object_detection\utils\config_util.py", line 90, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 127, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 95, in _prepare_value
    return compat.as_str_any(val)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\compat.py", line 110, in as_str_any
    return as_str(value)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\compat.py", line 87, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 2816: invalid start byte

The folder path has been named differently, but I think that is not be the cause. I don't know how to solve this problem..... please help me!!

**Comment by b15040612** [comment]
I have encountered the same problem. Have you solved it

**Comment by leegunwoo9708** [comment]
solved it???
