### ISSUE TITLE
non_max_suppression() got an unexpected keyword argument 'score_threshold'

### ISSUE THREAD

**Issue by Salindakrish** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#127]
While I following the ReadMe.txt , after i start to train the same data set in this tutorial  i got the error as 
non_max_suppression() got an unexpected keyword argument 'score_threshold'

_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING:tensorflow:From /home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/platform/app.py:126: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From /home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/legacy/trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "legacy/train.py", line 184, in <module>
    tf.app.run()
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/legacy/trainer.py", line 290, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/slim-0.1-py3.6.egg/deployment/model_deploy.py", line 193, in create_clones
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/legacy/trainer.py", line 203, in _create_losses
    prediction_dict = detection_model.predict(images, true_image_shapes)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 680, in predict
    self._anchors.get(), image_shape, true_image_shapes))
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 767, in _predict_second_stage
    anchors, image_shape_2d, true_image_shapes)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1234, in _postprocess_rpn
    clip_window=clip_window)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/core/post_processing.py", line 402, in batch_multiclass_non_max_suppression
    parallel_iterations=parallel_iterations)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/utils/shape_utils.py", line 228, in static_or_dynamic_map_fn
    return tf.map_fn(fn, elems, dtype, parallel_iterations, back_prop)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 413, in map_fn
    swap_memory=swap_memory)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3202, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2940, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2877, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 403, in compute
    packed_fn_values = fn(packed_values)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/core/post_processing.py", line 378, in _single_image_nms_fn
    additional_fields=per_image_additional_fields)
  File "/home/salinda/anaconda3/envs/sectionDetect/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/core/post_processing.py", line 150, in multiclass_non_max_suppression
    score_threshold=score_thresh)
TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'

i executed the code 
python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

what could be the issue. what  i did to resolve

- set the $PYTHONPATH again
- python setup build and installed
-executed the setup in slim folder too

**Comment by umeshsati54** [comment]
Update your tensorflow to v1.9.
