### ISSUE TITLE
No module named 'nets'

### ISSUE THREAD

**Issue by TechGenius28** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#150]
I am experiencing an issue when running the 'train.py' command.

This error keeps reoccurring:

  File "train.py", line 52, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\owner\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 30, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\Users\owner\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'

Please could somebody help me out.
Thanks

**Comment by vdsprakash** [comment]
once keep the defintion of the model_builder.py and faster_rcnn_inception_resnet_v2_feature_extractor.py

**Comment by vdsprakash** [comment]
> i have same problem too. any solution?

I can solve your problem, once share me your project directory list.

**Comment by venkateshbabusekar** [comment]
run this command 
set PYTHONPATH=C:\tensorflow1\models
set PYTHONPATH=C:\tensorflow1\models\research
set PYTHONPATH=C:\tensorflow1\models\research\slim


run the following commands from the C:\tensorflow1\models\research directory:


C:\tensorflow1\models\research> python setup.py build
C:\tensorflow1\models\research> python setup.py install

**Comment by nickguimaraes** [comment]
I was having the same error and this solved my problem 
https://github.com/tensorflow/models/issues/1842#issuecomment-377925135

**Comment by vdsprakash** [comment]
keep the nets folder in the object detection folder and change your importing code to 

from object_dectection.nets import (your_required_python file or class/function in python file)

**Comment by Akshaysharma29** [comment]
keep the nets folder in the object detection folder 
nets folder is present in research/slim directory

**Comment by iggy12345** [comment]
in the C:\tensorflow1\models\research\slim directory run
python setup.py build
python setup.py install

models/research/slim HAS ITS OWN setup.py!!!!!!!!!!!!!

**Comment by AlanNaoto** [comment]
> in the C:\tensorflow1\models\research\slim directory run
> python setup.py build
> python setup.py install
> 
> models/research/slim HAS ITS OWN setup.py!!!!!!!!!!!!!

Worked perfectly! Thanks a lot.

**Comment by rejj1234** [comment]
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\regie\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 35, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\Users\regie\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'

How can I fix this error?

**Comment by AlanNaoto** [comment]
> Traceback (most recent call last):
> File "train.py", line 51, in 
> from object_detection.builders import model_builder
> File "C:\Users\regie\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 35, in 
> from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
> File "C:\Users\regie\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in 
> from nets import inception_resnet_v2
> ModuleNotFoundError: No module named 'nets'
> 
> How can I fix this error?

That's because your train.py script is not finding the scripts from the nets folder. You should do as 
iggy12345 said and install those packages to the python you are using.

**Comment by rejj1234** [comment]
Thank you very much.

**Comment by harsathAI** [comment]
> in the C:\tensorflow1\models\research\slim directory run
> python setup.py build
> python setup.py install
> 
> models/research/slim HAS ITS OWN setup.py!!!!!!!!!!!!!

IT WORKS FLAWLESSLY!!!!! THANK YOU SO VERY MUCH

**Comment by MohammadDabbas** [comment]
Hi guys I'm having a similar error when I'm trying to run the training using this command:
`python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_coco.config`
 
this is the error that I'm having:
`Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 35, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\tensorflow1\models\research\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'` 

note: the setup.py file is already exist in the **slim** folder directory
plz guys help me out

**Comment by Itachi-Uchia** [comment]
@MohammadDabbas did you get the solution???
Bcz im getting the same scenario

**Comment by Itachi-Uchia** [comment]
> > in the C:\tensorflow1\models\research\slim directory run
> > python setup.py build
> > python setup.py install
> > models/research/slim HAS ITS OWN setup.py!!!!!!!!!!!!!
> 
> IT WORKS FLAWLESSLY!!!!! THANK YOU SO VERY MUCH

Brother I have the setup file but the 'install' wont run having the error as 

"could not create 'build':Cannot create a file when that file already exits"

If you know the solution then plz help

**Comment by SiddharthSingi** [comment]
> in the C:\tensorflow1\models\research\slim directory run
> python setup.py build
> python setup.py install
> models/research/slim HAS ITS OWN setup.py!!!!!!!!!!!!!
> 
> IT WORKS FLAWLESSLY!!!!! THANK YOU SO VERY MUCH
> 
> Brother I have the setup file but the 'install' wont run having the error as
> "could not create 'build':Cannot create a file when that file already exits"
> If you know the solution then plz help

Same problem here, if anyone has a solution then please post it. I have tried the solutions mentioned above

**Comment by kamal0803** [comment]
> > in the C:\tensorflow1\models\research\slim directory run
> > python setup.py build
> > python setup.py install
> > models/research/slim HAS ITS OWN setup.py!!!!!!!!!!!!!
> > IT WORKS FLAWLESSLY!!!!! THANK YOU SO VERY MUCH
> > Brother I have the setup file but the 'install' wont run having the
> > "could not create 'build':Cannot create a file when that file already exits"
> > If you know the solution then plz help
> 
> Same problem here, if anyone has a solution then please post it. I have tried the solutions mentioned above
Same problem

**Comment by SiddharthSingi** [comment]
Solution:
@kamal0803 
If you open python on your shell, run `import sys` and then `print(sys.path)` you will see a list of all the PYTHONPATH items in a list. To remove this error, this list must include a path to the slims, models and research directory. You can try `set PYTHONPATH=path_name_to_directory`. However if that does not work then you can also consider manually adding the pathname by going on My PC --> Properties -->Advanced System Settings --> Environment Variables and then add a new variable in System Variables.

This worked for me, also remember that even after you have added the pathnames, you will need to restart the shell or sometimes even the PC for it to reflect of sys.path

**Comment by kamal0803** [comment]
> Solution:
> @kamal0803
> If you open python on your shell, run `import sys` and then `print(sys.path)` you will see a list of all the PYTHONPATH items in a list. To remove this error, this list must include a path to the slims, models and research directory. You can try `set PYTHONPATH=path_name_to_directory`. However if that does not work then you can also consider manually adding the pathname by going on My PC --> Properties -->Advanced System Settings --> Environment Variables and then add a new variable in System Variables.
> 
> This worked for me, also remember that even after you have added the pathnames, you will need to restart the shell or sometimes even the PC for it to reflect of sys.path

![github](https://user-images.githubusercontent.com/42574558/59082847-8e389400-8912-11e9-9a3a-da7c3446efe6.JPG)

![Screenshot (19)](https://user-images.githubusercontent.com/42574558/59082884-b4f6ca80-8912-11e9-85fa-1602bea8bf34.png)


![Screenshot (21)](https://user-images.githubusercontent.com/42574558/59082895-bcb66f00-8912-11e9-81b5-3150e72d71e5.png)


I tried your solution, but its still not working..Please give another solution to this problem

**Comment by kamal0803** [comment]
> Solution:
> @kamal0803
> If you open python on your shell, run `import sys` and then `print(sys.path)` you will see a list of all the PYTHONPATH items in a list. To remove this error, this list must include a path to the slims, models and research directory. You can try `set PYTHONPATH=path_name_to_directory`. However if that does not work then you can also consider manually adding the pathname by going on My PC --> Properties -->Advanced System Settings --> Environment Variables and then add a new variable in System Variables.
> 
> This worked for me, also remember that even after you have added the pathnames, you will need to restart the shell or sometimes even the PC for it to reflect of sys.path

Also, I am using a CPU version of tensorflow.

**Comment by SiddharthSingi** [comment]
I am also using a CPU version, but that should not be an issue, where have you saved the environment variable, mine is saved like this:
![PYTHONPATH](https://user-images.githubusercontent.com/26694585/59083765-3c920880-8916-11e9-8805-6fceffc07f47.png)

And also on your cmd, run `python` then `import sys` then `print(sys.path)`.
You may have added your paths to PATH variable but you need to add it to PYTHONPATH variable in the environment variables like in the image above

**Comment by kamal0803** [comment]
> I am also using a CPU version, but that should not be an issue, where have you saved the environment variable, mine is saved like this:
> ![PYTHONPATH](https://user-images.githubusercontent.com/26694585/59083765-3c920880-8916-11e9-8805-6fceffc07f47.png)
> 
> And also on your cmd, run `python` then `import sys` then `print(sys.path)`.
> You may have added your paths to PATH variable but you need to add it to PYTHONPATH variable in the environment variables like in the image above

Sir,

Its still not working. Please help. I have sent the screenshots

Can it be a possibility that the files might been corrupt because of so many hit and trials.??



![Screenshot (24)](https://user-images.githubusercontent.com/42574558/59090589-ccda4880-892a-11e9-8384-f95939cb653e.png)

![Screenshot (26)](https://user-images.githubusercontent.com/42574558/59090600-d2d02980-892a-11e9-9330-3dd50ffecf80.png)

![Screenshot (27)](https://user-images.githubusercontent.com/42574558/59090607-d9f73780-892a-11e9-8c89-3e1ea886223a.png)

**Comment by SiddharthSingi** [comment]
Can you check in your folders if you have the nets folder inside slim directory?

**Comment by kamal0803** [comment]
Yes sir

![Screenshot (28)](https://user-images.githubusercontent.com/42574558/59092213-9ef70300-892e-11e9-8357-b8a853a71d10.png)

**Comment by kamal0803** [comment]
> Can you check in your folders if you have the nets folder inside slim directory?

Sir,the error I got, I checked it on github..The link to its solution is

https://github.com/tensorflow/models/issues/5138

But i am not able to find a solution 
Please help.

**Comment by lintujizoarakal777** [comment]
> run this command
> set PYTHONPATH=C:\tensorflow1\models
> set PYTHONPATH=C:\tensorflow1\models\research
> set PYTHONPATH=C:\tensorflow1\models\research\slim
> 
> run the following commands from the C:\tensorflow1\models\research directory:
> 
> C:\tensorflow1\models\research> python setup.py build
> C:\tensorflow1\models\research> python setup.py install

Super bro...... Thank you soooooo much

**Comment by rejj1234** [comment]
you should do the setpython path so that the error will disappear.

**Comment by tamasino52** [comment]
I'm already do that. But ModuleNotFoundError: No module named 'nets' message still occurs

**Comment by rejj1234** [comment]
make sure your directory is correct

**Comment by kamal0803** [comment]
@tamasino52
There might be a possibility that the files must have got corrupt. In this case, do everything from scratch and u will get the desired result. It happened the same with me.

**Comment by aliakgoz** [comment]
> I'm already do that. But " No module named 'nets' " message still occurs

try this
import os
os.environ['PYTHONPATH']=os.environ['PYTHONPATH']+':/content/models/research/slim'

**Comment by ramapsam** [comment]
> set PYTHONPATH=C:\tensorflow1\models\research\slim

i'm already do like this but this appear 

this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt: Not found: FindFirstFile failed for: C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28 : The system cannot find the path specified.
; No such process

anny solution?

**Comment by aliakgoz** [comment]
> > set PYTHONPATH=C:\tensorflow1\models\research\slim
> 
> i'm already do like this but this appear
> 
> this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt: Not found: FindFirstFile failed for: C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28 : The system cannot find the path specified.
> ; No such process
> 
> anny solution?

Are you sure from the path (C:\tensorflow1\models\research\slim)?

**Comment by ramapsam** [comment]
> > > set PYTHONPATH=C:\tensorflow1\models\research\slim
> > 
> > 
> > i'm already do like this but this appear
> > this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
> > tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt: Not found: FindFirstFile failed for: C:/tensorflow1/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28 : The system cannot find the path specified.
> > ; No such process
> > anny solution?
> 
> Are you sure from the path (C:\tensorflow1\models\research\slim)?

yes exactly like this
run this command
set PYTHONPATH=C:\tensorflow1\models
set PYTHONPATH=C:\tensorflow1\models\research
set PYTHONPATH=C:\tensorflow1\models\research\slim

run the following commands from the C:\tensorflow1\models\research directory:

C:\tensorflow1\models\research> python setup.py build
C:\tensorflow1\models\research> python setup.py install

after that i'm running this command 
python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
and error appear

**Comment by Mekatroniktr** [comment]
run this command

set PYTHONPATH=C:\tensorflow1\models
set PYTHONPATH=C:\tensorflow1\models\research
set PYTHONPATH=C:\tensorflow1\models\research\slim
**!!! also>** set PYTHONPATH=C:\tensorflow1\models\research\slim\net

run the following commands from the C:\tensorflow1\models\research directory:

C:\tensorflow1\models\research> python setup.py build
C:\tensorflow1\models\research> python setup.py install

**Comment by realDeve** [comment]
The mistake I made was using setup.py instead of **python setup.py**

**Comment by r901Player** [comment]
For those who had such an error: "could not create 'build':Cannot create a file when that file already exits"
when trying to build the setup.py in the slim folder. You need to delete a file called 'BUILD" in the slim folder.
and it will work.

**Comment by olarapio** [comment]
I solved this error by copying nets and deployment directories to the directory where train.py is

**Comment by yajinwuzl** [comment]
> For those who had such an error: "could not create 'build':Cannot create a file when that file already exits"
> when trying to build the setup.py in the slim folder. You need to delete a file called 'BUILD" in the slim folder.
> and it will work.
@Rams901 Your answer helped me！！！，thanks!

**Comment by chiragp007** [comment]
if you are using Jupyter Notebook and using Linux sys

download [tensorflow-models](https://github.com/tensorflow/models)

and then write this in your Notebook

sys.path.append("/home/Roy/Downloads/models-master/research/slim/")

I solved my problem with this

hope it helps
