### ISSUE TITLE
Unable to generate TFRrecord: getting error : TypeError: None has type NoneType, but expected one of: int, long : 

### ISSUE THREAD

**Issue by venkateshbabusekar** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#159]
(tensorflow2) C:\tensorflow2\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\babus\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 80, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\Users\babus\Anaconda3\envs\tensorflow2\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\utils\dataset_util.py", line 26, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long

**Comment by Burgomehl** [comment]
You have to convert your class names from a string to an integer. In my file is a method called class_text_to_int(row_label). Át that point i had to check for my class names and return a Int.

**Comment by Gotfeurdom** [comment]
> You have to convert your class names from a string to an integer
Where ?

>In my file is a method called class_text_to_int(row_label). Át that point i had to check for my class names and return a Int.
What file ?
At which point ?
Check what, where, when ?

**Comment by Burgomehl** [comment]
In generate_tfrecord.py 

My information are from: https://3sidedcube.com/guide-retraining-object-detection-models-tensorflow/
The following script from: https://github.com/Swaini/object_detection_retraining
The position you have to change is in method def class_text_to_int(row_label):


"""
Usage:
  # From tensorflow/models/
  # Create train data:
  python generate_tfrecord.py --input_csv=data/train_labels.csv  --output_tfrecord=train.record
  # Create test data:
  python generate_tfrecord.py --input_csv=data/test_labels.csv  --output_tfrecord=test.record
"""
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

import os
import io
import pandas as pd
import tensorflow as tf

from PIL import Image
from object_detection.utils import dataset_util
from collections import namedtuple, OrderedDict
import argparse


# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'Your_label':
        return 1
    if row_label == 'your_sceond_label':
        return 2
    .... 
    else:
        None


def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]


def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

    filename = group.filename.encode('utf8')
    image_format = b'jpg'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []

    for index, row in group.object.iterrows():
        xmins.append(row['xmin'] / width)
        xmaxs.append(row['xmax'] / width)
        ymins.append(row['ymin'] / height)
        ymaxs.append(row['ymax'] / height)
        classes_text.append(row['class'].encode('utf8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example


def main(_):

     # Taking command line arguments from users
    parser = argparse.ArgumentParser()
    parser.add_argument('-in', '--input_csv', help='define the input xml file', type=str, required=True)
    parser.add_argument('-out', '--output_tfrecord', help='define the output file ', type=str, required=True)
    args = parser.parse_args()
    writer = tf.python_io.TFRecordWriter(args.output_tfrecord)
    path = os.path.join(os.getcwd(), 'JPEGImages')
    examples = pd.read_csv(args.input_csv)
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), args.output_tfrecord)
    print('Successfully created the TFRecords: {}'.format(output_path))


if __name__ == '__main__':
    tf.app.run()

**Comment by Gotfeurdom** [comment]
> 
> 
> In generate_tfrecord.py
> 
> My information are from: https://3sidedcube.com/guide-retraining-object-detection-models-tensorflow/
> The following method is from: https://github.com/Swaini/object_detection_retraining
> The position you have to change is in method def class_text_to_int(row_label): (Line 26)
> 
> `def class_text_to_int(row_label): if row_label == 'Your_label': return 1 if row_label == 'your_sceond_label': return 2 .... else: None`

Actually this function is there by default and the tutorial specifically tells us to modify it according to our dataset.

However, I noticed that I mistyped my classes as I forgot that the first letter of my classes in the labeling program were upper case while I put them in lower case in the function.
Now this step seems to work fine.

**Comment by janekzimoch** [comment]
I got the same error. 

The problem for me was that when selecting and labeling regions i mispeled one of the categories. (so had 7 categories instead of 6)
The solution was to go over .csv file and find that misspeled category

**Comment by bipulneupane** [comment]
Can the classes be numbers?

def class_text_to_int(row_label):
    if row_label == '0':
        return 1
    elif row_label == '1':
        return 2
    elif row_label == '2':
        return 3
    elif row_label == '3':
        return 4
    elif row_label == '4':
        return 5
    elif row_label == '5':
        return 6
    elif row_label == '6':
        return 7
    elif row_label == '7':
        return 8
    elif row_label == '8':
        return 9
    elif row_label == '9':
        return 10
    else:
        return 0

I am having the same problem while i am trying to detect numbers.
