### ISSUE TITLE
Jupyter notebook error

### ISSUE THREAD

**Issue by charlie2108** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#176]
ImportError: Traceback (most recent call last):
  File "c:\users\mohammed rafid\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\mohammed rafid\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\mohammed rafid\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\mohammed rafid\anaconda3\envs\tensorflow1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\mohammed rafid\anaconda3\envs\tensorflow1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help

**Comment by janekzimoch** [comment]
I had the same problem, which i solved just now. 

If you have CUDA 10 and cuDNN for CUDA 10 you have to downgrade both down to CUDA 9.0 and respective cuDNN, as tensorflow doesn't support CUDA 10 just yet.

**Comment by ZeroOneTV** [comment]
If you have issues relative to DLL import when trying to import TensorFlow or training the model, you need to check your Protopuf version. The error happens when you have 3.6.1 version installed with tensorflow(in my case, GPU). It can easily be resolved by using version 3.6.0 instead. 
If you using ANACONDA, you only downgrade version, otherwise, donwload the 3.6.0 version of Protobuf to resolve this.
