### ISSUE TITLE
Training abruptly stops

### ISSUE THREAD

**Issue by kartikverma1** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#18]
Hi, 

First of all, thank you for this amazing tutorial, by far one of the best that I have come across. 

Unfortunately for me, there is an issue which I am not sure why it is occurring and I am hoping you can help me out. 

When I am running the training, it is abruptly stopping after some time. For the first time it ran till step 500 with a checkpoint at 319. When I ran it again, it stopped at step 876.  Why is this happening? 

Here is the message that I get. 

INFO:tensorflow:global step 875: loss = 0.2293 (0.922 sec/step)
INFO:tensorflow:global step 876: loss = 0.8595 (1.031 sec/step)
INFO:tensorflow:global step 876: loss = 0.8595 (1.031 sec/step)
2018-04-07 10:50:16.610307: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1273] OP_REQUIRES failed at cwise_ops_common.h:245 : Resource exhausted: OOM when allocating tensor with shape[3,3,576,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.ResourceExhaustedError'>, OOM when allocating tensor with shape[3,3,576,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[Node: ArithmeticOptimizer/clip_grads/clip_by_norm_151/mul_square = Square[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/Conv/Conv2D_grad/tuple/control_dependency_1/_2525)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: ToInt32_1/_2424 = _Send[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3425_ToInt32_1", _device="/job:localhost/replica:0/task:0/device:GPU:0"](ToInt32_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.ResourceExhaustedError'>, OOM when allocating tensor with shape[3,3,576,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[Node: ArithmeticOptimizer/clip_grads/clip_by_norm_151/mul_square = Square[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/Conv/Conv2D_grad/tuple/control_dependency_1/_2525)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: ToInt32_1/_2424 = _Send[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3425_ToInt32_1", _device="/job:localhost/replica:0/task:0/device:GPU:0"](ToInt32_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,3,576,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[Node: ArithmeticOptimizer/clip_grads/clip_by_norm_151/mul_square = Square[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/Conv/Conv2D_grad/tuple/control_dependency_1/_2525)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: ToInt32_1/_2424 = _Send[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3425_ToInt32_1", _device="/job:localhost/replica:0/task:0/device:GPU:0"](ToInt32_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 167, in <module>
    tf.app.run()
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 163, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\tensorflow1\models\research\object_detection\trainer.py", line 370, in train
    saver=saver)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 769, in train
    sess, train_op, global_step, train_step_kwargs)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\contrib\slim\python\slim\learning.py", line 487, in train_step
    run_metadata=run_metadata)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,3,576,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[Node: ArithmeticOptimizer/clip_grads/clip_by_norm_151/mul_square = Square[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/Conv/Conv2D_grad/tuple/control_dependency_1/_2525)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: ToInt32_1/_2424 = _Send[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3425_ToInt32_1", _device="/job:localhost/replica:0/task:0/device:GPU:0"](ToInt32_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

(tensorflow1) C:\tensorflow1\models\research\object_detection>

**Comment by kartikverma1** [comment]
Thanks @alhparsa for replying! But I do have a GPU. I have NVIDIA GeForce 940MX on my laptop. How do I train the model on a GPU? 
I will try to make the batch size smaller as well.

**Comment by alhparsa** [comment]
All I see here is that it is trying to use your CPU rather than your GPU. Try using the following code see if you encounter any errors:

```
import tensorflow as tf
with tf.device('/gpu:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

```

If you don't then put tf.device('gpu:0') before the code and then run it again, see if that helps.

**Comment by kartikverma1** [comment]
Thanks @alhparsa . The above code runs just fine with a GPU. I am using tensorflow-gpu. I added tf.device('gpu:0') but as it turn out my RAM may not be enough. The object detector code tries to run it on a GPU and gives out this warning (which I missed earlier) 

Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

So, correct me if I am wrong here: 
- It is switching to CPU because GPU doesn't have enough RAM. 

I also noticed that the tutorial says that use images for training which are around 200kb. I checked my image sizes, they around 2 mb. Do you think that might be a reason for memory insufficiency? If I resize the images, will it improve? 

Thank you for your time and patience. I really appreciate it.

**Comment by alhparsa** [comment]
Not a problem at all. Yea, you're right. In that case tensorflow is trying to load the data into your Ram instead of your GPU VRAM and using your CPU to train the model which is more time consuming and less efficient. Still I believe you can use your original pictures to train model, but you need to use way smaller batches, since each is loaded to the memory (VRAM/RAM) and then they get processed. The problem with resizing your images is that you need to label them again, since the xml files generated by labelImg contains the (x,y) of the upper left corner and lower right corner of the label which both are based on the pixel location. Unless you write a script to change that for each file. I can provide you with a script if you decided to take that route.

**Comment by n2ballroy** [comment]
I am a python rookie and am having trouble figuring out how to implement the fix you detailed a couple of days ago.

What file in this repository needs your edit below?

import tensorflow as tf
with tf.device('/gpu:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

**Comment by alhparsa** [comment]
@n2ballroy Just run that code in your python IDE to see if you have the right kind of tensorflow set up or not. The reason for that is to test wether tensorflow can find your gpu or not.

**Comment by F4H4D-87** [comment]
@alhparsa i am having the same problem as @kartikverma1 i am using gtx 1060 how can i fix this problem 
can you please help me it is very urgent );
