### ISSUE TITLE
need some help here: ~/Object_Detection_API/models/research/object_detection/training/labelmap.pbtxt; No such file or directory

### ISSUE THREAD

**Issue by bishopAL** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#181]
I test it on Ubuntu 18.04, tensorlfow 1.10 and it works well on Jupyter tutorial. But when I run this:
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

and I got this error:
```

WARNING:tensorflow:From /home/bingbing/anaconda3/envs/ob_env/lib/python3.5/site-packages/tensorflow/python/platform/app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1101 12:19:09.538238 140313625900864 tf_logging.py:125] From /home/bingbing/anaconda3/envs/ob_env/lib/python3.5/site-packages/tensorflow/python/platform/app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From /home/bingbing/Object_Detection_API/models/research/object_detection/legacy/trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1101 12:19:09.587111 140313625900864 tf_logging.py:125] From /home/bingbing/Object_Detection_API/models/research/object_detection/legacy/trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "/home/bingbing/anaconda3/envs/ob_env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/bingbing/anaconda3/envs/ob_env/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/bingbing/Object_Detection_API/models/research/object_detection/legacy/trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/bingbing/Object_Detection_API/models/research/object_detection/legacy/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/home/bingbing/Object_Detection_API/models/research/object_detection/builders/dataset_builder.py", line 123, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "/home/bingbing/Object_Detection_API/models/research/object_detection/data_decoders/tf_example_decoder.py", line 297, in __init__
    default_value=''),
  File "/home/bingbing/Object_Detection_API/models/research/object_detection/data_decoders/tf_example_decoder.py", line 59, in __init__
    label_map_proto_file, use_display_name=False)
  File "/home/bingbing/Object_Detection_API/models/research/object_detection/utils/label_map_util.py", line 164, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/home/bingbing/Object_Detection_API/models/research/object_detection/utils/label_map_util.py", line 133, in load_labelmap
    label_map_string = fid.read()
  File "/home/bingbing/anaconda3/envs/ob_env/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/home/bingbing/anaconda3/envs/ob_env/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/bingbing/anaconda3/envs/ob_env/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ~/Object_Detection_API/models/research/object_detection/training/labelmap.pbtxt; No such file or directory
```

In fact that labelmap.pbtxt file do exist in that directory. I dont know how to fix this, thank you for your helping!

**Comment by bishopAL** [comment]
Sorry, problem is solved. Here, '~/' can't to be used. Change '~/' to '/home/username/' to fix this problem
