### ISSUE TITLE
Are you planning to try "model_main.py" again instead of "train.py"

### ISSUE THREAD

**Issue by anonym24** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#184]
I suppose "model_main.py" should work better and mb then even fixed some errors which can affect speed/accuracy of models

**Comment by anonym24** [comment]
I see "model_main.py" wants cocoapi

For Windows we can install from https://github.com/philferriere/cocoapi

**Comment by anonym24** [comment]
but it fails with next errors `TypeError: can't pickle dict_values objects`

https://github.com/tensorflow/models/issues/5719

**Comment by anonym24** [comment]
Seems this error can be solved by
https://github.com/guildai/models/commit/d88f1fb9cad472c38149f208b086ca90c1da0856
https://github.com/tensorflow/models/issues/4780#issuecomment-405441448

**Comment by anonym24** [comment]
Solved and it works normal after some configuration: https://github.com/tensorflow/models/issues/5719#issuecomment-437323963

So SSD Models can be train normally with `model_train.py`, with legacy `train.py` you can get OOM errors

**Comment by dscha09** [comment]
@anonym24 How is model_main.py different from train.py?

**Comment by JanithT-Lboro** [comment]
where is this model_train.py file?

**Comment by cemicel** [comment]
> where is this model_train.py file?

https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py

**Comment by anonym24** [comment]
@dscha09 I don't know but with legacy `train.py` you can get OOM errors while starting training and at some point of training

@JanithT-Lboro https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py

**Comment by JanithT-Lboro** [comment]
I was able to solve this problem by just using a PC with better specs.

**Comment by Futi7** [comment]
C:\tensorflow\models\research>python object_detection\model_main.py --pipeline_config_path=object_detection\training\ssd_mobilenet_v1_pets.config --model_dir=object_detection\images --num_train_steps=50000 --sample_1_of_n_eval_examples=1 --alsologtostderr
Traceback (most recent call last):
  File "object_detection\model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\eval_util.py", line 27, in <module>
    from object_detection.metrics import coco_evaluation
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\metrics\coco_evaluation.py", line 22, in <module>
    from object_detection.utils import object_detection_evaluation
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\utils\object_detection_evaluation.py", line 39, in <module>
    from object_detection.utils import label_map_util
  File "C:\Users\Fuat\AppData\Local\Programs\Python\Python35\lib\site-packages\object_detection\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'

I got this error.How can i fix it.I installed protobuf, compiled it, added to path.
OS:Windows 10
CPU:AMD A9 7th Gen.
Python version:3.6
Protobuf version:3.4.0

**Comment by johnneijzen** [comment]
so far what i had to make it work is use command pip install pycocotools then i had error with net import to fix that i used under slim folder use command 'python setup.py install' research/slim/setup.py i got that from this https://github.com/tensorflow/models/issues/5795

**Comment by dienhoa** [comment]
@Futi7 I'm not sure on windows but I think you can solve it by running
`protoc object_detection/protos/*.proto --python_out=.`

**Comment by johnneijzen** [comment]
this work great

**Comment by EdjeElectronics** [comment]
Hey @anonym24 , I know it's been a year, but thanks for your work on this issue! I'm still considering whether to update my guide to use model_main.py rather than train.py. It's a bummer that it doesn't log training information in the console by default. 

[This issue (TensorFlow #61000)](https://github.com/tensorflow/models/issues/6100) has some good information directly from a TensorFlow team member on the differences between train.py and model_main.py. From their comments, it sounds like there is no difference when using a normal PC for training.
