### ISSUE TITLE
Error while training ...

### ISSUE THREAD

**Issue by VanitarNordic** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#2]
Hi,

I came across your tutorial till training, but I get the following error:

Somebody said this is related to Python 3, but you have used the python 3 (3.6). maybe the Object detection API repo has changed since you prepared your own repo. Anyway I'm confused and can not go forward

```
WARNING:tensorflow:From D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\trainer.py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\utils\label_map_util.py", line 132, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 525, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 579, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 612, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 627, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 866, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 1229, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 1244, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\text_format.py", line 1263, in _ConsumeSingleByteString
    raise self.ParseError('Expected string but found: %r' % (text,))
google.protobuf.text_format.ParseError: 3:8 : Expected string but found: '‘'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\internal\python_message.py", line 1069, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\internal\python_message.py", line 1091, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\internal\decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 169, in <module>
    tf.app.run()
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 165, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\trainer.py", line 235, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 122, in get_next
    worker_index=FLAGS.task)).get_next()
  File "D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\builders\dataset_builder.py", line 140, in build
    label_map_proto_file=label_map_proto_file)
  File "D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\data_decoders\tf_example_decoder.py", line 143, in __init__
    use_display_name)
  File "D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\utils\label_map_util.py", line 149, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "D:\Image_Processing\TFOD\models-master\models-master\research\object_detection\utils\label_map_util.py", line 134, in load_labelmap
    label_map.ParseFromString(label_map_string)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Users\Hesam\AppData\Local\conda\conda\envs\tfod\lib\site-packages\google\protobuf\internal\python_message.py", line 1075, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

**Comment by VanitarNordic** [comment]
The problem has fixed. actually inside the label_map.pbtxt the name of the object must be enclosed with " " not ' '

Now I have a different problem. Although I have installed Cuda 9.0, but the model mostly train on CPU and very little on GPU

**Comment by EdjeElectronics** [comment]
Hmm, I'm not sure why it isn't utilizing your GPU as much as your CPU. There could be a number of different issues. Hopefully someone else will be able to chime in and help with that!

**Comment by EdjeElectronics** [comment]
I'm going to close this issue since the GPU usage issue is probably related to your computer rather than this tutorial.  If you do find the solution, please comment here!

**Comment by VanitarNordic** [comment]
No, the issue is open at tensorflow API side. anyway seems to not related to your repo and might belongs to the newer commits
