### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lzxc87499** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#200]
WARNING:tensorflow:From D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1129 10:12:28.133898  8332 tf_logging.py:125] From D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 272, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\tensorflow1\models\research\object_detection\utils\config_util.py", line 94, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 888, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1251, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1266, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1291, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_encoding.py", line 103, in CUnescape
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
  File "D:\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_encoding.py", line 103, in <genexpr>
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
IndexError: list index out of range

when I am training the error ih therer.
I have such a problem. but i dont know how to solve it, can you help me .thanks a lot!

**Comment by tsaigaga** [comment]
i have the same problem....

**Comment by zyb1996** [comment]
when I tried SSD,I have the same problem.

**Comment by SouradipBh** [comment]
Any update on this issue?

**Comment by VIPlearner** [comment]
Please any update on this issue
