### ISSUE TITLE
 step 4 

### ISSUE THREAD

**Issue by ramkkreddy14** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#205]
python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
issue with step 4 ...
im getting this error ...can you help me out here.....in step 4
Traceback (most recent call last):
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kiran\Anaconda3\envs\tf1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(tf1) C:\tf1\models\research\object_detection>﻿

**Comment by ZeroOneTV** [comment]
you need to check your Protobuf version. The error happens when you have 3.6.1 version installed with tensorflow(in my case, GPU). It can easily be resolved by using version 3.6.0 instead.
If you using ANACONDA, you only downgrade version, otherwise, donwload the 3.6.0 version of Protobuf to resolve this.

**Comment by ramkkreddy14** [comment]
It didnt solve the issue

**Comment by EdjeElectronics** [comment]
Please see #266 for how to resolve this issue.
