### ISSUE TITLE
Error after training the model

### ISSUE THREAD

**Issue by gangubai** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#209]
======================End of Report==========================
2019-01-05 22:23:39.845302: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "export_inference_graph.py", line 150, in <module>
    tf.app.run()
  File "/home/ankitakulkarni/anaconda3/envs/tensorflow1/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 146, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "/home/ankitakulkarni/anaconda3/envs/tensorflow1/lib/python3.5/site-packages/object_detection-0.1-py3.5.egg/object_detection/exporter.py", line 405, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "/home/ankitakulkarni/anaconda3/envs/tensorflow1/lib/python3.5/site-packages/object_detection-0.1-py3.5.egg/object_detection/exporter.py", line 334, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "/home/ankitakulkarni/anaconda3/envs/tensorflow1/lib/python3.5/site-packages/object_detection-0.1-py3.5.egg/object_detection/exporter.py", line 245, in write_graph_and_checkpoint
    saver.restore(sess, trained_checkpoint_prefix)
  File "/home/ankitakulkarni/anaconda3/envs/tensorflow1/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: training/model.ckpt-XXXX

Can someone please comment on this?please!!

**Comment by malowana** [comment]
“XXXX” in “model.ckpt-XXXX” should be replaced with the highest-numbered .ckpt file in the training folder

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w
