### ISSUE TITLE
train.py doesnt work with TensorFlow 1.12

### ISSUE THREAD

**Issue by mephisto83** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#239]
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

Window 10, cpu only.

tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\legacy\trainer.py:266: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 0 to match input file shards.
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py:80: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 280, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 134, in build
    config.input_path[:], input_reader_config)
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 80, in read_dataset
    sloppy=config.shuffle))
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1190, in apply
    dataset = transformation_func(self)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\experimental\ops\interleave_ops.py", line 87, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\ops\readers.py", line 134, in __init__
    cycle_length, block_length)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2714, in __init__
    super(InterleaveDataset, self).__init__(input_dataset, map_func)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2677, in __init__
    experimental_nested_dataset_support=True)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\data\ops\readers.py", line 200, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\ajporter\AppData\Local\Continuum\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 983, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

**Comment by cocopambag** [comment]
line 5, "main (from **main**) is deprecated and will be removed in a future version." is error?

**Comment by leccyril** [comment]
there is not the complete error

**Comment by visiodeibc** [comment]
Hey I know this won't help much but I had a exact same error
so I decided to do it all over again this is what i did differently

- didn't run
   C:\tensorflow1\models\research\object_detection> python sizeChecker.py --move
   somehow all my pics would go to the wrong data folder so i didn't run this
- made sure when i wrote labelmap.pbtxt file  there were no extra line at the end and such
- for "faster_rcnn_inception_v2_pets.config " file editing at 
   Line 132. Change num_examples to the number of images you have in the \images\test directory.
   I realized i putted number of training data not test 

and just crossed my finger but it seems like its training well so best of luck for you too! I hope it helps somehow....

**Comment by saichandrareddy1** [comment]
@mephisto83 have you got the answer

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w
