### ISSUE TITLE
AssertionError: `eval_dir` is missing.

### ISSUE THREAD

**Issue by ali0517** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#24]
Hi!
when I try to eval the model ,like this

> python object_detection/eval.py \
>     --logtostderr \
>     --pipeline_config_path=object_detection/VOC_car/ssd_mobilenet_v1_voc2012.config \
>     --checkpoint_dir=object_detection/VOC_car/ssd_mobilenet_train_logs \
>     --eval_dir=object_detection/VOC_car/ssd_mobilenet_val_logs \

then report errors  
```
Traceback (most recent call last):
  File "object_detection/eval.py", line 135, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\python3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "object_detection/eval.py", line 85, in main
    assert FLAGS.eval_dir, '`eval_dir` is missing.'
AssertionError: `eval_dir` is missing.
```

I can't understand it. so searching for help!

**Comment by ibrahim1611** [comment]
I am facing same error
