### ISSUE TITLE
Getting a type error when running train.py

### ISSUE THREAD

**Issue by 747Dragon** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#25]
getting this error when running train.py

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --
logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_in
ception_v2_pets.config
WARNING:tensorflow:From C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packa
ges\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tens
orflow.contrib.learn.python.learn.datasets.base) is deprecated and will be remov
ed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\trainer.
py:228: create_global_step (from tensorflow.contrib.framework.python.ops.variabl
es) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py"
, line 134, in load_labelmap
text_format.Merge(label_map_string, label_map)
File "C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packages\google\proto
buf\text_format.py", line 533, in Merge
descriptor_pool=descriptor_pool)
File "C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packages\google\proto
buf\text_format.py", line 587, in MergeLines
return parser.MergeLines(lines, message)
File "C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packages\google\proto
buf\text_format.py", line 620, in MergeLines
self._ParseOrMerge(lines, message)
File "C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packages\google\proto
buf\text_format.py", line 635, in _ParseOrMerge
self._MergeField(tokenizer, message)
File "C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packages\google\proto
buf\text_format.py", line 735, in _MergeField
merger(tokenizer, message, field)
File "C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packages\google\proto
buf\text_format.py", line 822, in _MergeMessageField
raise tokenizer.ParseErrorPreviousToken('Expected "%s".' % (end_token,))
google.protobuf.text_format.ParseError: 13:9 : Expected "}".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "train.py", line 167, in 
tf.app.run()
File "C:\Users\Grant\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\platform\app.py", line 126, in run
_sys.exit(main(argv))
File "train.py", line 163, in main
worker_job_name, is_chief, FLAGS.train_dir)
File "C:\tensorflow1\models\research\object_detection\trainer.py", line 235, i
n train
train_config.prefetch_queue_capacity, data_augmentation_options)
File "C:\tensorflow1\models\research\object_detection\trainer.py", line 59, in
create_input_queue
tensor_dict = create_tensor_dict_fn()
File "train.py", line 120, in get_next
dataset_builder.build(config)).get_next()
File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder
.py", line 153, in build
label_map_proto_file=label_map_proto_file)
File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example
decoder.py", line 233, in _init
use_display_name)
File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py"
, line 151, in get_label_map_dict
label_map = load_labelmap(label_map_path)
File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py"
, line 136, in load_labelmap
label_map.ParseFromString(label_map_string)
TypeError: a bytes-like object is required, not 'str'﻿

**Comment by CarlicosMar** [comment]
Hello how are you, could you help me with this error message, the same thing happens to me, have you found any solution?

**Comment by benaliali** [comment]
how did you fixe it? ;)

**Comment by mcsimenc** [comment]
I'm having a similar problem
https://stackoverflow.com/questions/54024958/colab-tutorial-transfer-learning-using-object-detection-why-typeerror-from-look
