### ISSUE TITLE
 Please help what is the problem

### ISSUE THREAD

**Issue by smalgan** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#252]
I don't understand that this problem comes out on the last step

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 27, in <module>
    from object_detection.builders import post_processing_builder
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\post_processing_builder.py", line 22, in <module>
    from object_detection.protos import post_processing_pb2
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\protos\post_processing_pb2.py", line 15, in <module>
    from object_detection.protos import calibration_pb2 as object__detection_dot_protos_dot_calibration__pb2
ImportError: cannot import name 'calibration_pb2' from 'object_detection.protos' (C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\protos\__init__.py)

**Comment by ykpramodh** [comment]
Same issue on tensorflow (1.12). Please let me know if you found a fix for this.

**Comment by ykpramodh** [comment]
Check out the fix for this at - 

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/249#issuecomment-474242473

**Comment by smalgan** [comment]
> Bunun için düzeltmeye göz atın -
> 
> [# 249 (yorum)](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/249#issuecomment-474242473)

I tried, but the problem didn't improve. Is there another method? help me! Please.

**Comment by Rajamohanreddyai** [comment]
hi,
check this one, run the below command from research path
you can do manually

protoc --python_out=. .\object_detection\protos\calibration.proto
protoc --python_out=. .\object_detection\protos\object_detection.protos
and verify below video
https://youtu.be/nZUxoHPFf4
