### ISSUE TITLE
Error while running the training part.. TypeError: resize_images() got an unexpected keyword argument 'preserve_aspect_r atio'

### ISSUE THREAD

**Issue by OmorFarukRakib** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#256]
Hello Sir, When i try to train it, it throws the following errors.. Please help me with the solution.

(tensorflow1) C:\Tensorflow1\models\research\object_detection>python train.py --
logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_in
ception_v2_pets.config
WARNING:tensorflow:From C:\Users\OFR\Anaconda3\envs\tensorflow1\lib\site-package
s\tensorflow\python\platform\app.py:124: main (from main) is deprecated and
will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\legacy\t
rainer.py:266: create_global_step (from tensorflow.contrib.framework.python.ops.
variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.

Traceback (most recent call last):
File "train.py", line 184, in 
tf.app.run()
File "C:\Users\OFR\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\pyt
hon\platform\app.py", line 124, in run
_sys.exit(main(argv))
File "C:\Users\OFR\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\pyt
hon\util\deprecation.py", line 136, in new_func
return func(*args, **kwargs)
File "train.py", line 180, in main
graph_hook_fn=graph_rewriter_fn)
File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line
291, in train
clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
File "C:\tensorflow1\models\research\slim\deployment\model_deploy.py", line 19
3, in create_clones
outputs = model_fn(*args, **kwargs)
File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line
186, in _create_losses
resized_image, true_image_shape = detection_model.preprocess(image)
File "C:\tensorflow1\models\research\object_detection\meta_architectures\faste
r_rcnn_meta_arch.py", line 543, in preprocess
parallel_iterations=self._parallel_iterations)
File "C:\tensorflow1\models\research\object_detection\utils\shape_utils.py", l
ine 237, in static_or_dynamic_map_fn
outputs = [fn(arg) for arg in tf.unstack(elems)]
File "C:\tensorflow1\models\research\object_detection\utils\shape_utils.py", l
ine 237, in 
outputs = [fn(arg) for arg in tf.unstack(elems)]
File "C:\tensorflow1\models\research\object_detection\core\preprocessor.py", l
ine 2264, in resize_to_range
lambda: _resize_portrait_image(image))
File "C:\Users\OFR\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\pyt
hon\util\deprecation.py", line 316, in new_func
return func(*args, **kwargs)
File "C:\Users\OFR\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\pyt
hon\ops\control_flow_ops.py", line 1894, in cond
orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
File "C:\Users\OFR\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\pyt
hon\ops\control_flow_ops.py", line 1752, in BuildCondBranch
original_result = fn()
File "C:\tensorflow1\models\research\object_detection\core\preprocessor.py", l
ine 2263, in 
lambda: _resize_landscape_image(image),
File "C:\tensorflow1\models\research\object_detection\core\preprocessor.py", l
ine 2245, in _resize_landscape_image
align_corners=align_corners, preserve_aspect_ratio=True)
TypeError: resize_images() got an unexpected keyword argument 'preserve_aspect_r
atio'

Please Help me to solve this problem. :(

**Comment by monocongo** [comment]
I was able to get past this error by commenting out that argument in `models\research\object_detection\corepreprocessor.py`. My training is still running so I'm not sure what if any effect this will have so this may or may not be an actual solution. See issue #258 for details (looks to be the same issue as this).

**Comment by OmorFarukRakib** [comment]
Did your model work properly? @monocongo

**Comment by monocongo** [comment]
Yes, it seems so, see the attached image of my TensorBoard output for the model that's been running for about 16 hours now. Soon I will check to see how well the trained model performs as a detector for the class of objects I've trained it for.

![tensorboard_training_0](https://user-images.githubusercontent.com/1328158/55078601-e7618d00-5070-11e9-814f-3d1573fbba23.png)

**Comment by OmorFarukRakib** [comment]
Thanks a lot.. mine is also training after some modification.. I was using the old repository which was used for the tutorial so i had to change many thing and finally its working ^_^ hope for the best.

**Comment by OmorFarukRakib** [comment]
@monocongo I trained my model well enough with good total loss and all but when i am about to create frozen inference graph it takes too short time to create it and it gives me horribly wrong detection result.
When i create frozen inference graph, it shows following message---- 
"Creating new thread pool with default inter op setting: 4. Tune using inter_op_
parallelism_threads for best performance.

May i know which version of CUDA, CUDNN, Tensorflow, Tensorflow-gpu you are using???
And are you using the latest tensorflow/model repository or any old version as used in the tutorial?

Thanks in advance.

**Comment by monocongo** [comment]
@OmorFarukRakib I do not have access to a GPU at the moment so I'm only using the CPU version. My model appears to have trained OK but I have yet to be able to test it since I am now seeing this error:

```
  File "C:\home\miniconda\envs\scw\lib\site-packages\tensorflow\python\framework\importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named GatherV2 in defined operations.
```

So I apologize I can't help you much, as I don't have too much more success than you do so far.  :(

**Comment by EdjeElectronics** [comment]
Hi @monocongo and @OmorFarukRakib , I also just ran in to this issue. Thanks for working to figure it out! Like @monocongo suggested, you can remove the preserve_aspect_ratio=True argument where it errors out in the \object_detection\core\preprocessor.py file. I just tried this and it seems to be working.

I will close this issue once I confirm that my model runs correctly with this fix.

**Comment by OmorFarukRakib** [comment]
Thank you @EdjeElectronics for replying. I also solved that problem, thanks to @monocongo . I did everything as instructed in the tutorial but my detection result is horrible. I got many errors through out the processes but able to solve them all but now i have zero idea what i did wrong.. I tried two times and detection result is same and horrible. 
Do you have any clue why might it be happening? :(
N.B: I am using my CPU to train and i am using the old model repository that you used for your tutorial. 


![56508647_2270557153203231_4372747972614553600_n](https://user-images.githubusercontent.com/38896577/55675313-85abe900-58e2-11e9-9113-1501f2183eb5.png)

**Comment by OmorFarukRakib** [comment]
Hello @EdjeElectronics  Could you please share your model.ckpt-53698.meta file or the whole training folder? I think my inference graph is not being created properly. I would check whether my model is broken or the inference graph. 
Thanks again.

**Comment by iqrammm** [comment]
@monocongo : I could not seem to find the coreprocessor.py
![error](https://user-images.githubusercontent.com/48657762/59671000-7a810d80-91ef-11e9-9193-1c8f89d601c0.png)

**Comment by shubhjha04578** [comment]
> Hi @monocongo and @OmorFarukRakib , I also just ran in to this issue. Thanks for working to figure it out! Like @monocongo suggested, you can remove the preserve_aspect_ratio=True argument where it errors out in the \object_detection\core\preprocessor.py file. I just tried this and it seems to be working.
> 
> I will close this issue once I confirm that my model runs correctly with this fix.

how you deleted that line preserve_aspect_ratio=true??? or you changed it to preserve_aspect_ratio=false? please tell me because my training is not done yet

**Comment by BraVader777** [comment]
you can remove the preserve_aspect_ratio=True argument where it errors out in the \object_detection\core\preprocessor.py file. 
so did you comment it out, remove it completely > I am currently getting errors on this
Please show the final script of code for the function 
  def _resize_portrait_image(image):
#     # resize a portrait image
    return tf.image.resize_images(
        image, tf.stack([max_dimension, min_dimension]), method=method,
        align_corners=align_corners, preserve_aspect_ratio=True)

**Comment by alfdnl** [comment]
After i remove  **preserve_aspect_ratio=True** i get this error.
AttributeError: module 'tensorflow' has no attribute 'init_scope'

**Comment by goncz** [comment]
What version of Tensorflow are you using? Try upgrading to 1.12, worked for me.

**Comment by Yagamilighto4** [comment]
OmorFarukRakib can you explain me please what did you do to run the train , i got the same issue :( and i am stuck

**Comment by Yagamilighto4** [comment]
@OmorFarukRakib can you explain me please what did you do to run the train , i got the same issue :( and i am stuck

**Comment by apatsekin** [comment]
@Yagamilighto4 
There was no `preserve_aspect_ratio` argument in TF 1.9.0. Apparently you are using old TF version with newer object detection API version. Update your TF to the most recent 1.x version.
