### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'batch_gather' while Exporting Inference Graph

### ISSUE THREAD

**Issue by OmorFarukRakib** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#257]
(tensorflow1) C:\Tensorflow1\models\research\object_detection>python export_infe
rence_graph.py --input_type image_tensor --pipeline_config_path training/faster_
rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-26
16 --output_directory inference_graph
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\predicto
rs\heads\box_head.py:93: calling reduce_mean (from tensorflow.python.ops.math_op
s) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "export_inference_graph.py", line 156, in <module>
    tf.app.run()
  File "C:\Users\OFR\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\pyt
hon\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 152, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 465,
in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 368,
in _export_inference_graph
    graph_hook_fn=graph_hook_fn)
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 335,
in build_detection_graph
    output_collection_name=output_collection_name)
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 314,
in _get_outputs_from_inputs
    output_tensors, true_image_shapes)
  File "C:\tensorflow1\models\research\object_detection\meta_architectures\faste
r_rcnn_meta_arch.py", line 1180, in postprocess
    mask_predictions=mask_predictions)
  File "C:\tensorflow1\models\research\object_detection\meta_architectures\faste
r_rcnn_meta_arch.py", line 1644, in _postprocess_box_classifier
    tf.batch_gather(refined_decoded_boxes_batch, class_ids), axis=2)
AttributeError: module 'tensorflow' has no attribute 'batch_gather'

**Comment by AlexTaylorones** [comment]
tensorflow must be 1.10.0 and more

**Comment by OmorFarukRakib** [comment]
mine is 1.10 and still showing the same error.  should i upgrade the version? wont it have any effect on other files?

**Comment by SHADOWMOOON** [comment]
I am also facing the same problems. It seems that the 'batch_gather' function is not Declarated in the tensorflow-gpu(I am using the version of 1.9.0)

**Comment by SHADOWMOOON** [comment]
I just Upgrade the tensorflow-gpu to 1.12.0 and my problems solved...Hope this will help u too.
