### ISSUE TITLE
ValueError: Unknown field calibration_config.

### ISSUE THREAD

**Issue by Samjith888** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#261]
I have trained successfully before two weeks for my other project, after that i have installed tensorflow-GPU (without uninstalling tensorflow-cpu 1.9.0). Now i ran the training section for my other orject annd i got the error Getting the following error 'ValueError: Unknown field calibration_config.'. Then i have uninstalled tensorflow-gpu and ran the training. buti'm getting the same error again.

`[Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Sa\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\Sa\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\Sa\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\object_detection-0.1-py3.6.egg\object_detection\legacy\trainer.py", line 24
9, in train
    detection_model = create_model_fn()
  File "C:\Users\Sa\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py",
 line 124, in build
    add_summaries)
  File "C:\Users\Sa\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py",
 line 446, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)

  File "C:\Users\Sa\AppData\Local\Programs\Python\Python36\lib\site-pack
ages\object_detection-0.1-py3.6.egg\object_detection\builders\post_processing_bu
ilder.py", line 63, in build
    if post_processing_config.HasField('calibration_config'):
ValueError: Unknown field calibration_config.](url)`

Used the following versions
Tensorflow 1.9.0 CPU

@EdjeElectronics @azylinski @HiCraigChen @mgh3326

**Comment by Walid-Ahmed** [comment]
I am having the same error.
Any lick you solved it

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w


you can able to find solution in this video,.,.,.,.

you need to manually run the calibration protoc

**Comment by Rajamohanreddyai** [comment]
hi,

check this one, run the below command from research path

protoc --python_out=. .\object_detection\protos\calibration.proto

and verify below video

https://youtu.be/nZUxoHPFf4w
