### ISSUE TITLE
 Expected identifier or number, got <.1:1 : '<html>

### ISSUE THREAD

**Issue by EliasMontini** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#264]
Running the following instruction I found    
raise self.ParseError('Expected identifier or number, got %s.' % result)
': Expected identifier or number, got <.1:1 : '<html>

instruction: (tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

Complete issue:
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\utils\config_util.py", line 98, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 574, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 631, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 654, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 676, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 744, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "C:\Users\elias\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1214, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
': Expected identifier or number, got <.1:1 : '<html>

Any idea how to solve it? 
Thank you

**Comment by carlestecno** [comment]
https://github.com/tensorflow/tensorflow/issues/17129#issuecomment-458507428

From this link I´ve changed object-detection.pbtxt and add in "item"

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w

Hello,
it is very clear the path you specified was not available or else wrong, in the faster_rcnn_inception_v2_pets.config file.

use forward shlash ( / ) for train.record path, test.record path and labelmap.pbtxt and finetune checkpoint path, and verify it should be full path like

C:/Users/Divin/tensorflow/workspace/training/labelmap.pbtxt

use forward shlash ( / )

**Comment by EliasMontini** [comment]
Hello,
I will take a look.
Thank you very much for the reply.
Elias
