### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection.models.ssd_mobilenet_v1_keras_feature_extractor'

### ISSUE THREAD

**Issue by MohammadDabbas** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#265]
Hi, while running the training I'm getting this error:
`Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 47, in <module>
    from object_detection.models.ssd_mobilenet_v1_keras_feature_extractor import SSDMobileNetV1KerasFeatureExtractor
ModuleNotFoundError: No module named 'object_detection.models.ssd_mobilenet_v1_keras_feature_extractor'`

note: I'm using the ssd_mobilenet_v1 model
thanks in advance

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w
