### ISSUE TITLE
First step cannot be zero issue

### ISSUE THREAD

**Issue by PCIHD** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#272]
I am facing this issue saying first step shouldnt  be zero , now if change is made to the config file in the config file  at line 92 a new problem arises the model doesnt train at all

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "D:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\legacy\trainer.py", line 304, in train
    train_config.optimizer)
  File "D:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\optimizer_builder.py", line 52, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "D:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\optimizer_builder.py", line 115, in _create_learning_rate
    learning_rate_sequence, config.warmup)
  File "D:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\utils\learning_schedules.py", line 160, in manual_stepping
    raise ValueError('First step cannot be zero.')
ValueError: First step cannot be zero.

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w

**Comment by MRo47** [comment]
change the attribute step: 0 to step: 1 in the optimizer section of the pipeline.config file.
my guess is that it was changed in newer tensor flow object detector versions (training starts at step 1).
