### ISSUE TITLE
google.protobuf.text_format.ParseError with run train.py

### ISSUE THREAD

**Issue by ttzhub** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#276]
please help me to solve this problem,thanks~

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\config_util.py", line 96, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 574, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 631, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 654, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 676, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 801, in _MergeField
    merger(tokenizer, message, field)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 875, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\protobuf\text_format.py", line 768, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 198:3 : Message type "object_detection.protos.InputReader" has no field named "input_path".

**Comment by Rajamohanreddyai** [comment]
Hi, check this link
https://youtu.be/nZUxoHPFf4w

Hello,
it is very clear the path you specified was not available or else wrong, in the faster_rcnn_inception_v2_pets.config file.

use forward shlash ( / ) for train.record path, test.record path and labelmap.pbtxt and finetune checkpoint path, and verify it should be full path like

C:/Users/Divin/tensorflow/workspace/training/labelmap.pbtxt

use forward shlash ( / )
