### ISSUE TITLE
Couldn't build proto file into descriptor pool

### ISSUE THREAD

**Issue by xiiaoyu** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#279]
How do i solve this problem?

Traceback (most recent call last):
  File "export_inference_graph.py", line 102, in <module>
    from object_detection import exporter
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 27, in <module>
    from object_detection.builders import post_processing_builder
  File "C:\tensorflow1\models\research\object_detection\builders\post_processing_builder.py", line 22, in <module>
    from object_detection.protos import post_processing_pb2
  File "C:\tensorflow1\models\research\object_detection\protos\post_processing_pb2.py", line 25, in <module>
    dependencies=[object__detection_dot_protos_dot_calibration__pb2.DESCRIPTOR,])
  File "C:\Users\Xiiaoyu\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "object_detection/protos/post_processing.proto":
  object_detection/protos/post_processing.proto: Import "object_detection/protos/calibration.proto" has not been loaded.
  object_detection.protos.PostProcessing.calibration_config: "object_detection.protos.CalibrationConfig" seems to be defined in "protos/calibration.proto", which is not imported by "object_detection/protos/post_processing.proto".  To use it here, please add the necessary import.

**Comment by Rajamohanreddyai** [comment]
check this link

https://youtu.be/nZUxoHPFf4w
