### ISSUE TITLE
object_detection_image.py error

### ISSUE THREAD

**Issue by magatonman** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#284]
after following the readme file and Youtube video, I run object_detectioni_image.py(and webcam, too), but it made this error and stop working

Traceback (most recent call last):
File "D:\tensorflow1\models\research\object_detection\Object_detection_image.py", line 66,
in <module>
serialized_graph=fid.read()
File "D:\Anaconda\envs\tensor\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
self._preread_check()
File "D:\Anaconda\envs\tensor\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in_preread_check
compat.as_bytes(self.__name), 1024 * 512, status)
File "D:\Anaconda\envs\tensor\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528,in __exit__
c_api.TF_GetCode(self.status.status))

What's wrong?

**Comment by swayam69** [comment]
Check the path name. File is in the wrong location
