### ISSUE TITLE
Issues while Generating TFrecords

### ISSUE THREAD

**Issue by mssudarsan** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#290]
While generating tfrecords, I got the following errors

I'm attaching the log here :

python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record

Traceback (most recent call last):
  File "generate_tfrecord.py", line 107, in <module>
    tf.app.run()
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensor\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 96, in main
    grouped = split(examples, 'filename')
  File "generate_tfrecord.py", line 48, in split
    gb = df.groupby(group)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensor\lib\site-packages\pandas\core\generic.py", line 7632, in groupby
    observed=observed, **kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensor\lib\site-packages\pandas\core\groupby\groupby.py", line 2110, in groupby
    return klass(obj, by, **kwds)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensor\lib\site-packages\pandas\core\groupby\groupby.py", line 360, in __init__
    mutated=self.mutated)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\tensor\lib\site-packages\pandas\core\groupby\grouper.py", line 578, in _get_grouper
    raise KeyError(gpr)
KeyError: 'filename'

Help me to solve this error.

Thanks in Advance

**Comment by mssudarsan** [comment]
I fixed it my self :)

**Comment by AlanZhangozha** [comment]
> I fixed it my self :)

Could you share your experience, please, how did you fixed it? Thanks!

**Comment by Marto37** [comment]
Could any of you share the solution? I'm having the same problem right now. Thanks!

**Comment by technofreak98** [comment]
The generate_tfrecord.py file requires the "filename" keyword in the train_labels.csv and test_labels.csv files which is missing.
The "train_labels.csv" file must contain column name on the first line. For TensorFlow Object Detection API the column name is,
"**filename,width,height,class,xmin,ymin,xmax,ymax**".
Add this on the first line of the csv file and it must work.

> Could any of you share the solution? I'm having the same problem right now. Thanks!
