### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by mihuzz** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#295]
### I cant run training
`\models\research\object_detection>python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\HP\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "legacy/train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\HP\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\HP\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "legacy/train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "D:\Lesson8\models\research\object_detection\utils\config_util.py", line 97, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "C:\Users\HP\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\HP\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\HP\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: training/faster_rcnn_inception_v2_pets.config : \udccd\udce5 \udcf3\udce4\udce0\udce5\udcf2\udcf1\udcff \udced\udce0\udce9\udcf2\udce8 \udcf3\udcea\udce0\udce7\udce0\udced\udced\udcfb\udce9 \udcf4\udce0\udce9\udceb.
; No such file or directory`

**Comment by tiachachat** [comment]
copy the two files : faster_rcnn_inception_v2_pets.config & labelmap.pbtxt from C:\tensorflow1\models\research\object_detection\training 
and past them in C:\tensorflow1\models\research\object_detection\legacy\training

or use \object_detection> python model_main.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

**Comment by oumaimafadi** [comment]
Please im getting the same error, and i've been struggling for days trying all the solutions suggested!
any other suggestion can be very help!soooss!
Thank you!

**Comment by lt14** [comment]
help :

Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 181, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow2\models\research\object_detection\legacy\trainer.py", line 398, in train
    include_global_step=False))
  File "C:\tensorflow2\models\research\object_detection\utils\variables_helper.py", line 139, in get_variables_available_in_checkpoint
    ckpt_reader = tf.train.NewCheckpointReader(checkpoint_path)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 636, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 648, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on C: /tensorflow2/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28/model.ckpt: Not found: FindFirstFile failed for: C: /tensorflow2/models/research/object_detection/faster_rcnn_inception_v2_coco_2018_01_28 : El sistema no puede encontrar la ruta especificada.
; No such process

**Comment by oumaimafadi** [comment]
Still having the same problem!
Any suggestion can help lots of people
