### ISSUE TITLE
Trouble generating TFRecord 

### ISSUE THREAD

**Issue by hweelin-yeo** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#297]
A FileNotFound error is made, but it's not the input CSV file (test_labels.csv) that can't be found:

```
python generate_tfrecord.py --csv_input=images\test_labels.csv --image_dir=images\test --output_path=test.record
Traceback (most recent call last):
  File "generate_tfrecord.py", line 103, in <module>
    tf.app.run()
  File "/home/hweelinyeo/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 91, in main
    examples = pd.read_csv(FLAGS.csv_input)
  File "/home/hweelinyeo/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/hweelinyeo/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/hweelinyeo/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/hweelinyeo/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/hweelinyeo/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
**FileNotFoundError: [Errno 2] File b'imagestest_labels.csv' does not exist: b'imagestest_labels.csv**'
```

Any help would be appreciated!

**Comment by hweelin-yeo** [comment]
Turns out it's a syntactical error.

**Comment by Petros626** [comment]
> 
> 
> Turns out it's a syntactical error.

which one?
