### ISSUE TITLE
Object_detection_video.py:  ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ccv26** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#304]
Basically have made it through the whole tutorial but get the following error when trying to run any of the object_detection_###.py scripts from IDLE. The error looks similar to what the video shows when the script is run from the desktop, but I have made sure to open IDLE from the cmd prompt with the tensorflow1 conda environment activated. 

Has anyone found a fix or run into this problem running the object detection scripts?

>>> 
 RESTART: C:\tensorflow1\models\research\object_detection\Object_detection_video.py 
Traceback (most recent call last):
  File "C:\tensorflow1\models\research\object_detection\Object_detection_video.py", line 21, in <module>
    import cv2
  File "C:\Anaconda3\envs\tensorflow1\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by ccv26** [comment]
Could someone please help me with this? Any advice would be much appreciated. I get this error for both the "Object_detection_image.py" file AND the "Object_detection_video.py" files.

**Comment by ccv26** [comment]
after many grueling hours working on this, the solutions here worked: 
https://www.researchgate.net/post/How_to_import_cv2_into_anaconda_spyder_Python_36

Download these files and restart your computer: 
https://www.microsoft.com/en-us/software-download/mediafeaturepack

Good luck to you, hopefully this helps someone.

**Comment by HaFred** [comment]
I occurred the same problem. I solved it by following the appendix & **reinstalling jupyter notebook in the working conda envs**.
Hope it helps.
