### ISSUE TITLE
out of memory while using webcam to detect 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#316]
when I execute webcam script i.e. [this](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/Object_detection_webcam.py)

I'm using Faster RCNN with Resnet 101 coco model with 2080Ti. The video/webcam is full HD. I also tried converting video in same resolution that images were trained on(my dataset) 600x343 but I still get same error

I get an error: 
```
 python stf_new.py
2019-07-09 15:11:35.179313: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2019-07-09 15:11:35.209618: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2663270000 Hz
2019-07-09 15:11:35.213981: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5642d13e24e0 executing computations on platform Host. Devices:
2019-07-09 15:11:35.214030: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "stf_new.py", line 68, in <module>
    sess = tf.Session(graph=detection_graph)
  File "/home/redtwo/anaconda3/envs/nstest2/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/redtwo/anaconda3/envs/nstest2/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 11521884160
```

**Comment by AbhimanyuAryan** [comment]
works great. Thanks solved it :)

**Comment by whuhxb** [comment]
@azylinski 
How to solve this problem? I have also met this error with tensorflow.

/site-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 34089730048

**Comment by AbhimanyuAryan** [comment]
> @azylinski 
> How to solve this problem? I have also met this error with tensorflow.
> 
> /site-packages/tensorflow/python/client/session.py", line 676, in __init__
>     self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
> tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 34089730048

Either make the batch size smaller or lower image resolution
