### ISSUE TITLE
train.py error 

### ISSUE THREAD

**Issue by aidenmj** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#324]
(tensorflow_gpu) C:\TensorFlow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Users\THIS PC\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\THIS PC\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\THIS PC\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\TensorFlow\models\research\object_detection\legacy\trainer.py", line 249, in train
    detection_model = create_model_fn()
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 135, in build
    add_summaries)
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 521, in _build_faster_rcnn_model
    ) = post_processing_builder.build(frcnn_config.second_stage_post_processing)
  File "C:\TensorFlow\models\research\object_detection\builders\post_processing_builder.py", line 59, in build
    post_processing_config.batch_non_max_suppression)
  File "C:\TensorFlow\models\research\object_detection\builders\post_processing_builder.py", line 89, in _build_non_max_suppressor
    **if nms_config.soft_nms_sigma < 0.0:
AttributeError: soft_nms_sigma**
I can't find solution for it. Please help me

**Comment by oumaimafadi** [comment]
i tried to copy the training folder from object_detection to object-detection/legacy 
but no result! please try it or suggest any other solution!

**Comment by pdeman** [comment]
I have the same error, have you found a solution ?

**Comment by oumaimafadi** [comment]
not yet if u find something please let me know
