### ISSUE TITLE
Issue on Step 4

### ISSUE THREAD

**Issue by lucassrfreire** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#33]
I have a issue on Step 4. After the generate_tfrecords I receive the following error:(KeyError: filename). What show I do?

Traceback (most recent call last):
   File "generate_tfrecord.py", line 102, in <module>
     tf.app.run()
   File "C:\Users\Matheus Freire\AppData\Local\conda\conda\envs\tf15\lib\site- packages\tensorflow\python\platform\app.py", line 124, in run _sys.exit(main(argv))
   File "generate_tfrecord.py", line 91, in main
    grouped = split(examples, 'filename')
   File "generate_tfrecord.py", line 42, in split
     gb = df.groupby(group)
   File "C:\Users\Matheus Freire\AppData\Local\conda\conda\envs\tf15\lib\site- packages\pandas\core\generic.py", line 5162, in groupby
     **kwargs)
   File "C:\Users\Matheus Freire\AppData\Local\conda\conda\envs\tf15\lib\site- packages\pandas\core\groupby.py", line 1848, in groupby
     return klass(obj, by, **kwds)
   File "C:\Users\Matheus Freire\AppData\Local\conda\conda\envs\tf15\lib\site- packages\pandas\core\groupby.py", line 516, in _init_
     mutated=self.mutated)
   File "C:\Users\Matheus Freire\AppData\Local\conda\conda\envs\tf15\lib\site- packages\pandas\core\groupby.py", line 2934, in _get_grouper
     raise KeyError(gpr)
 KeyError: 'filename'

Thanks!

**Comment by lucassrfreire** [comment]
I solved editing the csv file. On cpu mode i should use csv separed in columns. In gpu mode just used the csv created by the scrip

**Comment by rish-16** [comment]
Hey there !

Have you solved it yet? I'm getting the same error with the 'filename' thing.
