### ISSUE TITLE
Problems with start to generate TFRECORD

### ISSUE THREAD

**Issue by mihuzz** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#331]
### FileNotFoundError: [Errno 2] File b'imagestrain_labels.csv' does not exist: b'imagestrain_labels.csv'
`Traceback (most recent call last):
  File "generate_tfrecord.py", line 108, in <module>
    tf.app.run()
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 96, in main
    examples = pd.read_csv(FLAGS.csv_input)
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/mihuzz/anaconda3/envs/tf/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'imagestrain_labels.csv' does not exist: b'imagestrain_labels.csv'`

**Comment by EdjeElectronics** [comment]
Looks like you missed a '\\' when running this command:
```
python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
```

**Comment by joselochelo** [comment]
Hi, I have the same problem and I cannot solve. I put this comand:

python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
