### ISSUE TITLE
error when training data in object detection with faster rcnn

### ISSUE THREAD

**Issue by cmesparta** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#349]
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\data_decoders\tf_example_decoder.py", line 32, in <module>
    slim_example_decoder = tf.contrib.slim.tfexample_decoder
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\__init__.py", line 45, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\cudnn_rnn\__init__.py", line 34, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 95, in <module>
    from tensorflow.contrib.rnn.python.ops.rnn_cell import *
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\rnn\python\ops\rnn_cell.py", line 24, in <module>
    from tensorflow.contrib.layers.python.layers import layers
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\layers\__init__.py", line 120, in <module>
    from tensorflow.contrib.layers.python.layers import *
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\layers\python\layers\__init__.py", line 33, in <module>
    from tensorflow.contrib.layers.python.layers.target_column import *
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\layers\python\layers\target_column.py", line 24, in <module>
    from tensorflow.contrib.losses.python.losses import loss_ops
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\losses\__init__.py", line 25, in <module>
    from tensorflow.contrib.losses.python import metric_learning
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\losses\python\metric_learning\__init__.py", line 25, in <module>
    from tensorflow.contrib.losses.python.metric_learning.metric_loss_ops import *
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\tensorflow\contrib\losses\python\metric_learning\metric_loss_ops.py", line 34, in <module>
    from sklearn import metrics
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\sklearn\metrics\__init__.py", line 7, in <module>
    from .ranking import auc
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\sklearn\metrics\ranking.py", line 35, in <module>
    from ..preprocessing import label_binarize
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\sklearn\preprocessing\__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\sklearn\preprocessing\_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\sklearn\utils\testing.py", line 718, in <module>
    import pytest
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\_pytest\assertion\__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\_pytest\assertion\rewrite.py", line 20, in <module>
    from _pytest.assertion import util
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\_pytest\assertion\util.py", line 5, in <module>
    import _pytest._code
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\_pytest\_code\__init__.py", line 2, in <module>
    from .code import Code  # noqa
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\_pytest\_code\code.py", line 11, in <module>
    import pluggy
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\pluggy\__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\pluggy\manager.py", line 6, in <module>
    import importlib_metadata
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\importlib_metadata\__init__.py", line 478, in <module>
    __version__ = version(__name__)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\importlib_metadata\__init__.py", line 445, in version
    return distribution(package).version
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\importlib_metadata\__init__.py", line 418, in distribution
    return Distribution.from_name(package)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\importlib_metadata\__init__.py", line 180, in from_name
    dist = next(dists, None)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\importlib_metadata\__init__.py", line 365, in <genexpr>
    for path in map(cls._switch_path, paths)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\site-packages\importlib_metadata\__init__.py", line 389, in _search_path
    if not root.is_dir():
  File "C:\Users\felix\Anaconda3\envs\py36\lib\pathlib.py", line 1348, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "C:\Users\felix\Anaconda3\envs\py36\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\tensorflow1\\models\\research\\object_detection\\ C:\\tensorflow1\\models\\research'

----------------------------------------------------------------------------------------------------------
i using windows 10
 anaconda 3.6.9
tensorflow 1.12.0 
tensorflow_gpu 1.2.0
cuda 9.0

**Comment by ProblemOng** [comment]
batch size?? faster rcnn only accept batch size with 1 pls try with batch size 1

**Comment by cmesparta** [comment]
> batch size?? faster rcnn only accept batch size with 1 pls try with batch size 1

hello, thank for reply, i have check my in faster_rcnn config, the batch_size are 1
