### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by chowtaprathiksha** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#350]
I am a beginner trying to test the existing model(SSD).
I have installed python 3.6 and tensorflow 1.6 and also necessary packages.
When i run Object_detection_image.py in object detection i am facing following problem which i am not able to understand:
>>> 
 RESTART: D:\IT\image_text\tensorflow1\models\research\object_detection\Object_detection_image.py 
Traceback (most recent call last):
  File "D:\IT\image_text\tensorflow1\models\research\object_detection\Object_detection_image.py", line 22, in <module>
    import tensorflow as tf
  File "C:\Users\IT User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\IT User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\IT User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\IT User\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
>>> 
I hope i would get better explanation for a beginner like me.
Thanks in Advance.

**Comment by aidoshacks** [comment]
It appears that you have either not installed cuda and cudnn properly or have an incompatible version. 
Table here should point you to the compatible versions: 
https://www.tensorflow.org/install/source#linux

**Comment by chowtaprathiksha** [comment]
Morning, have a good day
@aidoshacks thank you for the reply.
i am working with windows 7 system and have solved the error by upgrading the python version as well as same packages too.
