### ISSUE TITLE
ImportError: cannot import name 'flexible_grid_anchor_generator_pb2'

### ISSUE THREAD

**Issue by Ricftrw** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#361]
```
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\justf\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\builders\model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "C:\Users\justf\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\builders\anchor_generator_builder.py", line 22, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "C:\Users\justf\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\protos\anchor_generator_pb2.py", line 15, in <module>
    from object_detection.protos import flexible_grid_anchor_generator_pb2 as object__detection_dot_protos_dot_flexible__grid__anchor__generator__pb2
ImportError: cannot import name 'flexible_grid_anchor_generator_pb2'
```

is there a solution for this?

**Comment by EdjeElectronics** [comment]
In the big protoc command in [Step 2f](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#2f-compile-protobufs-and-run-setuppy), add this:

.\object_detection\protos\flexible_grid_anchor_generator.proto

You may also need to add ".\object_detection\protos\calibration.proto"

I removed these from the command a week ago because it caused me errors while I was working through the guide. It looks like I was working with an outdated version of the [models repository](https://github.com/tensorflow/models/tree/master/research/object_detection), though. I will change it back now!
