### ISSUE TITLE
Error please urgent help !

### ISSUE THREAD

**Issue by F4H4D-87** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#37]
i go this error then i did like (epratheeban ) i changed 167 line then i got another error

Traceback (most recent call last):
File "train.py", line 49, in 
from object_detection import trainer
File "C:\tensorflow1\models\research\object_detection\trainer.py", line 26, in 
from object_detection.builders import optimizer_builder
File "C:\tensorflow1\models\research\object_detection\builders\optimizer_builder.py", line 19, in 
from object_detection.utils import learning_schedules
File "C:\tensorflow1\models\research\object_detection\utils\learning_schedules.py", line 167
rate_index = tf.reduce_max(tf.where(tf.greater_equal(global_step, boundaries),
^
IndentationError: unindent does not match any outer indentation level

please help me i need it sooooooo bad

**Comment by EdjeElectronics** [comment]
You must have accidentally added a space or tab somewhere in the train.py script. Make sure the indentation level at line 167 is consistent with the other lines of code.
