### ISSUE TITLE
Cannot run generate_tfrecord.py

### ISSUE THREAD

**Issue by Noa20** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#380]
FileNotFoundError: [Errno 2] File b'imagestrain_labels.csv' does not exist: b'imagestrain_labels.csv'

Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "/opt/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 88, in main
    examples = pd.read_csv(FLAGS.csv_input)
  File "/opt/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/opt/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'imagestrain_labels.csv' does not exist: b'imagestrain_labels.csv'

**Comment by JulianOrteil** [comment]
What is the command you are using to run the Python script?

**Comment by Sarah906** [comment]
did you find any solution?
