### ISSUE TITLE
Updated Tutorial for Tensorflow 2.0?

### ISSUE THREAD

**Issue by Nightrain** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#383]
@EdjeElectronics  Thanks so much for this tutorial.  It hit the mark for me and lots of others it seems.   I have been scouring the web for tensorflow 2.0 object detection and found one tutorial.  Unfortunately it only had one class per picture, so it does not work for my needs.  Are there any plans in the near future for you to release a object detection tutorial on tensorflow 2.0? Or should I just stick with version 1.9 for any future work?

cheers

**Comment by EdjeElectronics** [comment]
Hi @Nightrain, it's on my To Do list to get this guide updated to work with TensorFlow v2.0. Unfortunately, the TensorFlow team themselves have not updated the Object Detection API code (which we clone from https://github.com/tensorflow/models/tree/master/research/object_detection in this guide) to work with TF v2.0.

For now, please continue using TF v1.X for object detection. I still like TF v1.13 because it is stable and  installable through Anaconda ("conda install tensorflow-gpu=1.13.1"). Installing it through Anaconda is nice because it will also automatically download and install the CUDA and cuDNN versions needed for the version of TF that you are using. It keeps the CUDA and cuDNN installations all within the virtual environment, so you don't need to worry about conflicting versions if you already had CUDA and cuDNN on your machine.

**Comment by Nightrain** [comment]
Hello @EdjeElectronics   Thanks for the quick response.  And the tip about using conda to install and automatically getting the correct CUDA and cuDNN in my Anaconda environment.  I do have one other question.  If i train the model using the GPU and then move the frozen graph to another machine.  Does that machine need the same video card?  Or is GPU only used for training?

**Comment by EdjeElectronics** [comment]
No problem! You caught me at a good time 😃. No, if you move the frozen graph to another machine, you do not need to use the same video card. The GPU is only used for training, once the graph is exported it will work with any other GPU. It will also work without a GPU on a CPU-only installation.

Unrelated to the GPU, the TensorFlow versions do need to match between the machine you trained the model on and the machine you want to deploy the model on.

**Comment by Nightrain** [comment]
Ok that sounds good to me.  I will certainly keep all that in mind.  Might be best if I can just clone my environment to the server.  Thanks again for the tutorial, it got my on my way, and the boss is happy so they are dreaming up more work for me.

**Comment by kirlein84** [comment]
Hi , i am sorry to hijack you thread , i tried to use Tensorflow 2.0 and got same error , by reading your feedback i downgraded to 1.13.1 (CPU version) , reproduce all step and stuck at this error , please kindly need your advise

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

```
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 170, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\tensorflow1\models\research\object_detection\trainer.py", line 275, in train
    train_config.load_all_detection_checkpoint_vars)
TypeError: restore_map() got an unexpected keyword argument 'from_detection_checkpoint'

```

**Comment by evanorb** [comment]
hi @EdjeElectronics , greetings from Indonesia, I just learned tensorflow a month ago and I can't continue the tutorial this part because of problems in the Object Detection API code from tensorflow has changed to tf2.0 and I don't really understand what should I change, can you do that help me with making a tutorial update with tf2.0?

**Comment by evanorb** [comment]
hi @EdjeElectronics , greetings from Indonesia, I just learned tensorflow a month ago and I can't continue the tutorial this part because of problems in the Object Detection API code from tensorflow has changed to tf2.0 and I don't really understand what should i changed, can you help me with making a tutorial update with tf2.0? Thanks a lot for your tutorial, your tutorial is the best, i can easy to understand your tutorial 👍👍
