### ISSUE TITLE
TypeError: expected bytes, Descriptor found

### ISSUE THREAD

**Issue by saqibshakeel035** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#418]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Windows 10)
- TensorFlow installed from (source):
- TensorFlow version: Tensorflow GPU Version 1.14.0
- Python version: 3.6.9
- Installed using conda:
- CUDA/cuDNN version: cuda_10.0.130_411.31_win10 / cudnn-10.0-windows10-x64-v7.4.1.5
- GPU model and memory: nvidia mx 250 with 2GB0

**Describe the problem**
I am folliwn the [Edge Electronics](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#1-install-anaconda-cuda-and-cudnn) github repository. At [step 2d. Set up new Anaconda virtual environment](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#2d-set-up-new-anaconda-virtual-environment)  I created a virtual environment using `conda create -n tensorflow1 pip python=3.6` 
The other commands I executed are:
`activate tensorflow1`
`python -m pip install --upgrade pip`
`pip install --ignore-installed --upgrade tensorflow-gpu==1.14.0`
After last command, when I try to import tensorflow, it get imported successfully but after running follwoing command,
`conda install -c anaconda protobuf` when I again try to import tensorflow, I get the following error. 
(tensorflow1) C:\>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\saqib\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 92, in <module>
    __module__ = 'tensorflow.core.framework.resource_handle_pb2'
TypeError: expected bytes, Descriptor found

I have tried everthing like removing the virtual environment and creating the new but still the same error. 
What mistake dou you think I am doing?
Any possible solution will be apppreciated.
Thanks in advance :) 
Looking forward for quick reply

**Comment by fearollchan** [comment]
It may be because of protobuf version conflict. 
like  1)conda install -c anaconda protobuf 2)  another protobuf installed by command pip. 
You can try to uninstall them and reinstall pip version protobuf. 
I met the problem when I run gernerate_tfrecord.py, and I uninstall and reinstall protobuf, finally it works
