### ISSUE TITLE
NO MODULE NAMED 'DEPLOYMENT'

### ISSUE THREAD

**Issue by TechGenius28** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#43]
Hi, I have been getting this problem when I try and train the ai. Please could somebody help me.
Thanks
Error:

`
(tensorflow1) C:\Users\owner\Documents\tensorflow1\models-master\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_resnet50_pets.config
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection import trainer
  File "C:\Users\owner\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py", line 33, in <module>
    from deployment import model_deploy
ModuleNotFoundError: No module named 'deployment'

`

**Comment by EdjeElectronics** [comment]
Hi, did you already try the steps listed in the tutorial's Appendix? https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#appendix-common-errors

**Comment by TechGenius28** [comment]
I went through the steps listed, but the same error occurred. Is there any other way to resolve this issue?

Thanks

**Comment by Abdou24MR** [comment]
its easy : 
in folder /models/research
~/.../models/research$ python setup.py build
~/.../models/research$ python setup.py install
2-
-this export commande in linux; if you are woking on windows check (2e. Configure PYTHONPATH environment variable) in : https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#2e-configure-pythonpath-environment-variable

$export PYTHONPATH=$PYTHONPATH:/home/najat/anaconda3/test22222222/models
$export PYTHONPATH=$PYTHONPATH:/home/najat/anaconda3/test22222222/models/research
$export PYTHONPATH=$PYTHONPATH:/home/najat/anaconda3/test22222222/models/research/slim

3- in folder /models/research/object_detection:
~/.../models/research/object_detection$ python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

thats all :+1:

**Comment by MinaYousryGhattas** [comment]
For windows  if you are using anaconda add slim folder to 
...\Anaconda3\envs\{Environment name}\Lib\site-packages\object_detection-0.1-py3.6.egg
and change 
`from deployment import model_deploy`
to 
`from slim.deployment import model_deploy`

**Comment by eshwarkamal** [comment]
> For windows if you are using anaconda add slim folder to
> ...\Anaconda3\envs\{Environment name}\Lib\site-packages\object_detection-0.1-py3.6.egg
> and change
> `from deployment import model_deploy`
> to
> `from slim.deployment import model_deploy`

can u tell how to open .egg file and change it
