### ISSUE TITLE
I have some trouble when I run the object_detection_tutorial.ipynb file

### ISSUE THREAD

**Issue by YuanTG** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#432]
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1349     try:
-> 1350       return fn(*args)
   1351     except errors.OpError as e:

e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1328                                    feed_dict, fetch_list, target_list,
-> 1329                                    status, run_metadata)
   1330 

e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    472             compat.as_text(c_api.TF_Message(self.status.status)),
--> 473             c_api.TF_GetCode(self.status.status))
    474     # Delete the underlying status object from memory otherwise it stays alive

InternalError: Blas SGEMM launch failed : m=22500, n=64, k=32
	 [[Node: FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_pointwise/BatchNorm/batchnorm/mul_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/Relu6, FeatureExtractor/MobilenetV1/Conv2d_1_pointwise/weights/read/_160__cf__163)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_77/Gather/Gather_2/_661 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6641_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_77/Gather/Gather_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayReadV3_4/_1)]]

During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)
<ipython-input-10-7fbe6a7c7e45> in <module>
     21       (boxes, scores, classes, num) = sess.run(
     22           [detection_boxes, detection_scores, detection_classes, num_detections],
---> 23         feed_dict={image_tensor: image_np_expanded})
     24       # Visualization of the results of a detection.
     25       vis_util.visualize_boxes_and_labels_on_image_array(

e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1126     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1127       results = self._do_run(handle, final_targets, final_fetches,
-> 1128                              feed_dict_tensor, options, run_metadata)
   1129     else:
   1130       results = []

e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1342     if handle is None:
   1343       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1344                            options, run_metadata)
   1345     else:
   1346       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1361         except KeyError:
   1362           pass
-> 1363       raise type(e)(node_def, op, message)
   1364 
   1365   def _extend_graph(self):

InternalError: Blas SGEMM launch failed : m=22500, n=64, k=32
	 [[Node: FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_pointwise/BatchNorm/batchnorm/mul_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/Relu6, FeatureExtractor/MobilenetV1/Conv2d_1_pointwise/weights/read/_160__cf__163)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_77/Gather/Gather_2/_661 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6641_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_77/Gather/Gather_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayReadV3_4/_1)]]

Caused by op 'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_pointwise/BatchNorm/batchnorm/mul_1', defined at:
  File "e:\anaconda3\envs\tensorflow1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda3\envs\tensorflow1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel\kernelapp.py", line 563, in start
    self.io_loop.start()
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "e:\anaconda3\envs\tensorflow1\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "e:\anaconda3\envs\tensorflow1\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "e:\anaconda3\envs\tensorflow1\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel\kernelbase.py", line 377, in dispatch_queue
    yield self.process_one()
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 225, in wrapper
    runner = Runner(result, future, yielded)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 714, in __init__
    self.run()
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\IPython\core\interactiveshell.py", line 3242, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-0d8b8f2357e8>", line 7, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\importer.py", line 554, in import_graph_def
    op_def=op_def)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "e:\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas SGEMM launch failed : m=22500, n=64, k=32
	 [[Node: FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_pointwise/BatchNorm/batchnorm/mul_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/Relu6, FeatureExtractor/MobilenetV1/Conv2d_1_pointwise/weights/read/_160__cf__163)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_77/Gather/Gather_2/_661 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6641_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ClipToWindow_77/Gather/Gather_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayReadV3_4/_1)]]

**Comment by YuanTG** [comment]
Can someone help me?

**Comment by maacofficial** [comment]
> Can someone help me?
Please continue without running jupyter!
