### ISSUE TITLE
Error. Help me

### ISSUE THREAD

**Issue by Kintaro96** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#44]
python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record

Error :
Traceback (most recent call last):
  File "generate_tfrecord.py", line 112, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 103, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 92, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\dataset_util.py", line 26, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long

**Comment by EdjeElectronics** [comment]
This error usually happens when it failed to load the image files in your images/test or images/train directory. Make sure you have specified the correct path to your files, and that the files are located in the correct place and have the correct file types.
