### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'

### ISSUE THREAD

**Issue by HajerAa** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#453]
Hi i faced this issue while running "python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config"

Traceback (most recent call last):
  File "train.py", line 52, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 47, in <module>
    from object_detection.models.ssd_mobilenet_edgetpu_feature_extractor import SSDMobileNetEdgeTPUFeatureExtractor
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\models\ssd_mobilenet_edgetpu_feature_extractor.py", line 19, in <module>
    from object_detection.models import ssd_mobilenet_v3_feature_extractor
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\models\ssd_mobilenet_v3_feature_extractor.py", line 25, in <module>
    from nets.mobilenet import mobilenet
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\nets\mobilenet\mobilenet.py", line 399, in <module>
    def global_pool(input_tensor, pool_op=tf.compat.v2.nn.avg_pool2d):
AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'

I'm using CPU
Tensorflow 1.13.1

**Comment by ZheQU-somfy** [comment]
Hi, I faced the same problem, did you solve it?

**Comment by HajerAa** [comment]
Yes i solved the issue by cloning the models-1.13.0

**Comment by ZheQU-somfy** [comment]
Could you please tell me how you solve this problem? Thanks

**Comment by maacofficial** [comment]
Because of your using tensorflow version and tensorflow models version difference. You should download right version from tensorflow models repository from [here](https://github.com/tensorflow/models/commits/master).
You can select version from branch section.

Example: İf you use TensorFlow 1.5.0 you should [download TensorFlow models r1.5.](https://github.com/tensorflow/models/tree/96e2c0eee5f44a3cc820f6dacd2c229e410ec2dc)
