### ISSUE TITLE
generator_tfrecord.py

### ISSUE THREAD

**Issue by HardworkingPig** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#466]
Traceback (most recent call last):
  File "generate_tfrecord.py", line 101, in <module>
    tf.app.run()
  File "C:\Users\Acer\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 92, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 81, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "C:\Users\Acer\Anaconda3\envs\tensorflow2\lib\site-packages\object_detection-0.1-py3.5.egg\object_detection\utils\dataset_util.py", line 26, in int64_list_feature
TypeError: None has type NoneType, but expected one of: int, long

I don't get why this show-up

**Comment by AmeyaUpalanchi** [comment]
# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'basketball':
        return 1
    elif row_label == 'shirt':
        return 2
    elif row_label == 'shoe':
        return 3
    else:
        return 0

Replace None with 0

**Comment by satyamedh** [comment]
please close the issue if it solved @HardworkingPig
