### ISSUE TITLE
Error when executing:  python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

### ISSUE THREAD

**Issue by jk0324** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#492]
Hello, i am now in the training part, but it shows the error below. Can you guys help me fix it? 
C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
2020-05-21 09:19:11.257360: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-05-21 09:19:11.418703: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From C:\Users\Hp\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\ops\distributions\distribution.py:265: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From C:\Users\Hp\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\ops\distributions\normal.py:274: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    import tensorflow as tf
  File "C:\Users\Hp\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\Hp\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\__init__.py", line 32, in <module>
    from tensorflow._api.v1 import app
  File "C:\Users\Hp\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\_api\v1\app\__init__.py", line 10, in <module>
    from tensorflow.python.platform.app import run
  File "C:\Users\Hp\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\platform\app.py", line 23, in <module>
    from absl.app import run as _run
  File "C:\Users\Hp\Anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 26, in <module>
    from object_detection import model_lib
  File "C:\tensorflow1\models\research\object_detection\model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "C:\tensorflow1\models\research\object_detection\eval_util.py", line 31, in <module>
    from object_detection.core import box_list_ops
  File "C:\tensorflow1\models\research\object_detection\core\box_list_ops.py", line 34, in <module>
    from object_detection.utils import ops
  File "C:\tensorflow1\models\research\object_detection\utils\ops.py", line 317, in <module>
    dtype=tf.float32):
AttributeError: module 'tensorflow' has no attribute 'float32'

**Comment by QuickLearner171998** [comment]
https://stackoverflow.com/questions/51654346/attributeerror-module-tensorflow-has-no-attribute-float32
