### ISSUE TITLE
error while xml_to_csv

### ISSUE THREAD

**Issue by andhana** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#5]
I have 150 files .xml in test directory and 563 files .xml in train directory. when i run xml_to_csv.py, i get an error like this:

```
$ python xml_to_csv.py 
Traceback (most recent call last):
  File "xml_to_csv.py", line 35, in <module>
    main()
  File "xml_to_csv.py", line 31, in main
    xml_df = xml_to_csv(image_path)
  File "xml_to_csv.py", line 10, in xml_to_csv
    tree = ET.parse(xml_file)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: junk after document element: line 3, column 1
```

can anyone help me fix this?

**Comment by pariharatul** [comment]
I too have been facing the same issue. Were you able to resolve this?

**Comment by andhana** [comment]
there is a typo or a directory image that does not match the .xml file. 
I checked one by one from the whole .xml file
