### ISSUE TITLE
ValueError: faster_rcnn_inception_v2 is not supported. See `model_builder.py`.

### ISSUE THREAD

**Issue by muditkhare10** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#515]
Hello,

I am facing below mentioned step will trying to run "**python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config**".

Tensorflow Version:- 2.1.0
Python Version:- 2.7.0
OS :- Window10

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

2020-08-05 21:57:27.148584: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found

2020-08-05 21:57:27.160441: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

WARNING:tensorflow:From C:\Users\MuditKhare\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W0805 21:57:33.450702 17004 deprecation.py:323] From C:\Users\MuditKhare\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\MuditKhare\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\MuditKhare\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\MuditKhare\anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\MuditKhare\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "train.py", line 183, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 248, in train
    detection_model = create_model_fn()
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 1016, in build
    add_summaries)
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 553, in _build_faster_rcnn_model
    _check_feature_extractor_exists(frcnn_config.feature_extractor.type)
  File "C:\tensorflow1\models\research\object_detection\builders\model_builder.py", line 243, in _check_feature_extractor_exists
    'Tensorflow'.format(feature_extractor_type))

ValueError: faster_rcnn_inception_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

Please help me to fix this issue.

Thanks,
Mudit Khare

**Comment by bm777** [comment]
Hi @muditkhare10 
for my case I used this [model_train.py](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py) from TensorFlow repo. And it worked for me.

**Comment by vermasrijan19** [comment]
@bm777 could you explain how you made it work?
I am at the point where i have tried use newer models etc, but always end up in some error or other, is there a way to make faster_rcnn_inception_v2 work with tf2?

**Comment by Gauravmak27** [comment]
@bm777 how exactly have you used model_train.py? I am facing same problem!

**Comment by vermasrijan19** [comment]
So i was having the same issue, for some reason github gave me notif for this last comment. You cannot run a TF1 Model with TF2, you need to use a TF2 models for TF2, instead of using model_train.py use model_maintf2.py

**Comment by selmazrg** [comment]
@vermasrijan19 how can I change it? sorry I'm a beginner and I don't see how to solve it

**Comment by vermasrijan19** [comment]
> 
> 
> @vermasrijan19 how can I change it? sorry I'm a beginner and I don't see how to solve it

just replace model_train.py with model_maintf2.py, rest of the command can be the same

**Comment by selmazrg** [comment]
@vermasrijan19 Sorry I dont understand, where do i change it? 
the command that I'm trying to run is :
>python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config

**Comment by bm777** [comment]
> > @vermasrijan19 how can I change it? sorry I'm a beginner and I don't see how to solve it
> 
> just replace model_train.py with model_maintf2.py, rest of the command can be the same

Yeah, you can use it like this. i used this LINK of [model_train.py](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py) from TensorFlow repo

`python model_train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config`


PS: for TF.2.X use model_traintf2.py and the other for TF.1.x

**Comment by selmazrg** [comment]
@bm777 Thanks for your reply, i tried to use model_traintf2.py and the other but I still have the same error :
 
File "C:\Users\anaconda3\envs\tensorflow\lib\site-packages\object_detection\builders\model_builder.py", line 246, in _check_feature_extractor_exists
    raise ValueError('{} is not supported. See `model_builder.py` for features '
ValueError: faster_rcnn_inception_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

**Comment by bm777** [comment]
Which version of TensorFlow are you using?

**Comment by selmazrg** [comment]
@bm777  tensorflow  2.4.0

**Comment by bm777** [comment]
Okay. Oh, you got these error because you were trying to use a model of TensorFlow1 on TensorFlow 2. This cause incompatibility. 
Now you have to use TensorFlow 2 model. You can find one [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)

For example, you can try with [THIS](http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8.tar.gz)

And let me know if it works :)

**Comment by selmazrg** [comment]
@bm777 Thanks a lot for your help,  i tried but now I have this error :
 
 File "C:\Users\zarga\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 101: invalid continuation byte

I'm going to try again I think I made a mistake, it's so difficult there is a new error a every step !

**Comment by bm777** [comment]
What  have you type on your terminal?

**Comment by selmazrg** [comment]
@bm777 python legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training\faster_rcnn_resnet50_cocos.config

**Comment by bm777** [comment]
@selmazrg  Okay, if we continue, we will get more error. 
For me, I used TensorFlow 1.7, and it worked, very well. you can try to downgrade version of you TensorFlow, or you can install TensorFlow in another Virtual environment. It will work, believe me.

**Comment by selmazrg** [comment]
@bm777 Thanks I will try this right know and hope it work!

**Comment by bm777** [comment]
@selmazrg  okay.

**Comment by punamgoyal2008** [comment]
i m facing the same problem.
i m already using TensorFlow 2 Detection Model Zoo.

Windows 10:
TensorFlow version: 2.6.0
Python version: 3.9.0
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: CUDA=11.2.0(network)  cudnn=8.1

when i run the following command on command prompt:
python Tensorflow\models\research\object_detection\model_main_tf2.py --model_dir=Tensorflow\workspace\models\faster_rcnn_resnet50 --pipeline_config_path=Tensorflow\workspace\models\faster_rcnn_resnet50\pipeline.config --num_train_steps=3000

the following error has shown:

2021-10-28 09:25:48.608665: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-10-28 09:25:48.608788: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-28 09:25:48.612351: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-21SGAAA
2021-10-28 09:25:48.612520: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-21SGAAA
2021-10-28 09:25:48.613081: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W1028 09:25:48.606194  4380 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I1028 09:25:48.606194  4380 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
INFO:tensorflow:Maybe overwriting train_steps: 3000
I1028 09:25:48.621771  4380 config_util.py:552] Maybe overwriting train_steps: 3000
INFO:tensorflow:Maybe overwriting use_bfloat16: False
I1028 09:25:48.621771  4380 config_util.py:552] Maybe overwriting use_bfloat16: False
Traceback (most recent call last):
  File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 115, in <module>
    tf.compat.v1.app.run()
  File "E:\dd\TFODCourse\rg1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 106, in main
    model_lib_v2.train_loop(
  File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\model_lib_v2.py", line 541, in train_loop
    detection_model = MODEL_BUILD_UTIL_MAP['detection_model_fn_base'](
  File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 1249, in build
    return build_func(getattr(model_config, meta_architecture), is_training,
  File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 400, in _build_ssd_model
    _check_feature_extractor_exists(ssd_config.feature_extractor.type)
  File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 266, in _check_feature_extractor_exists
    raise ValueError('{} is not supported. See `model_builder.py` for features '
ValueError:  is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

plz help me to resolve this error.

**Comment by mncdvalenzuela** [comment]
> i m facing the same problem. i m already using TensorFlow 2 Detection Model Zoo.
> 
> Windows 10: TensorFlow version: 2.6.0 Python version: 3.9.0 Bazel version (if compiling from source): GCC/Compiler version (if compiling from source): CUDA/cuDNN version: CUDA=11.2.0(network) cudnn=8.1
> 
> when i run the following command on command prompt: python Tensorflow\models\research\object_detection\model_main_tf2.py --model_dir=Tensorflow\workspace\models\faster_rcnn_resnet50 --pipeline_config_path=Tensorflow\workspace\models\faster_rcnn_resnet50\pipeline.config --num_train_steps=3000
> 
> the following error has shown:
> 
> 2021-10-28 09:25:48.608665: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found 2021-10-28 09:25:48.608788: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303) 2021-10-28 09:25:48.612351: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-21SGAAA 2021-10-28 09:25:48.612520: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-21SGAAA 2021-10-28 09:25:48.613081: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX AVX2 To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce. W1028 09:25:48.606194 4380 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce. INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',) I1028 09:25:48.606194 4380 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',) INFO:tensorflow:Maybe overwriting train_steps: 3000 I1028 09:25:48.621771 4380 config_util.py:552] Maybe overwriting train_steps: 3000 INFO:tensorflow:Maybe overwriting use_bfloat16: False I1028 09:25:48.621771 4380 config_util.py:552] Maybe overwriting use_bfloat16: False Traceback (most recent call last): File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 115, in tf.compat.v1.app.run() File "E:\dd\TFODCourse\rg1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 312, in run _run_main(main, args) File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 258, in _run_main sys.exit(main(argv)) File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 106, in main model_lib_v2.train_loop( File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\model_lib_v2.py", line 541, in train_loop detection_model = MODEL_BUILD_UTIL_MAP['detection_model_fn_base']( File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 1249, in build return build_func(getattr(model_config, meta_architecture), is_training, File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 400, in _build_ssd_model _check_feature_extractor_exists(ssd_config.feature_extractor.type) File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 266, in _check_feature_extractor_exists raise ValueError('{} is not supported. See `model_builder.py` for features ' ValueError: is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow
> 
> plz help me to resolve this error.

Hi, I'm having the same error as you. Have you found a solution to this?

**Comment by vermasrijan19** [comment]
I dont remember the old solution but, as far as i remember verify all the versions of things u are using are compatible with each other. I think it was something to do with people using tf1 models with tf2 so make sure that is sorted. (the video guide uses tf1) and most people that end up with this error are using tf2. (tf= tensorflow)

**Comment by HridoyHazard** [comment]
> i m facing the same problem. i m already using TensorFlow 2 Detection Model Zoo.
> 
> Windows 10: TensorFlow version: 2.6.0 Python version: 3.9.0 Bazel version (if compiling from source): GCC/Compiler version (if compiling from source): CUDA/cuDNN version: CUDA=11.2.0(network) cudnn=8.1
> 
> when i run the following command on command prompt: python Tensorflow\models\research\object_detection\model_main_tf2.py --model_dir=Tensorflow\workspace\models\faster_rcnn_resnet50 --pipeline_config_path=Tensorflow\workspace\models\faster_rcnn_resnet50\pipeline.config --num_train_steps=3000
> 
> the following error has shown:
> 
> 2021-10-28 09:25:48.608665: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found 2021-10-28 09:25:48.608788: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303) 2021-10-28 09:25:48.612351: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-21SGAAA 2021-10-28 09:25:48.612520: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-21SGAAA 2021-10-28 09:25:48.613081: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX AVX2 To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce. W1028 09:25:48.606194 4380 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce. INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',) I1028 09:25:48.606194 4380 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',) INFO:tensorflow:Maybe overwriting train_steps: 3000 I1028 09:25:48.621771 4380 config_util.py:552] Maybe overwriting train_steps: 3000 INFO:tensorflow:Maybe overwriting use_bfloat16: False I1028 09:25:48.621771 4380 config_util.py:552] Maybe overwriting use_bfloat16: False Traceback (most recent call last): File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 115, in tf.compat.v1.app.run() File "E:\dd\TFODCourse\rg1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 312, in run _run_main(main, args) File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 258, in _run_main sys.exit(main(argv)) File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 106, in main model_lib_v2.train_loop( File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\model_lib_v2.py", line 541, in train_loop detection_model = MODEL_BUILD_UTIL_MAP['detection_model_fn_base']( File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 1249, in build return build_func(getattr(model_config, meta_architecture), is_training, File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 400, in _build_ssd_model _check_feature_extractor_exists(ssd_config.feature_extractor.type) File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 266, in _check_feature_extractor_exists raise ValueError('{} is not supported. See `model_builder.py` for features ' ValueError: is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow
> 
> plz help me to resolve this error.

havin the same error. anyone fixed it yet?

**Comment by dk-teknologisk-jlan** [comment]
> i m facing the same problem. i m already using TensorFlow 2 Detection Model Zoo.
> 
> Windows 10: TensorFlow version: 2.6.0 Python version: 3.9.0 Bazel version (if compiling from source): GCC/Compiler version (if compiling from source): CUDA/cuDNN version: CUDA=11.2.0(network) cudnn=8.1
> 
> when i run the following command on command prompt: python Tensorflow\models\research\object_detection\model_main_tf2.py --model_dir=Tensorflow\workspace\models\faster_rcnn_resnet50 --pipeline_config_path=Tensorflow\workspace\models\faster_rcnn_resnet50\pipeline.config --num_train_steps=3000
> 
> the following error has shown:
> 
> 2021-10-28 09:25:48.608665: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found 2021-10-28 09:25:48.608788: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303) 2021-10-28 09:25:48.612351: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-21SGAAA 2021-10-28 09:25:48.612520: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-21SGAAA 2021-10-28 09:25:48.613081: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX AVX2 To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce. W1028 09:25:48.606194 4380 cross_device_ops.py:1387] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce. INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',) I1028 09:25:48.606194 4380 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',) INFO:tensorflow:Maybe overwriting train_steps: 3000 I1028 09:25:48.621771 4380 config_util.py:552] Maybe overwriting train_steps: 3000 INFO:tensorflow:Maybe overwriting use_bfloat16: False I1028 09:25:48.621771 4380 config_util.py:552] Maybe overwriting use_bfloat16: False Traceback (most recent call last): File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 115, in tf.compat.v1.app.run() File "E:\dd\TFODCourse\rg1\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef) File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 312, in run _run_main(main, args) File "E:\dd\TFODCourse\rg1\lib\site-packages\absl\app.py", line 258, in _run_main sys.exit(main(argv)) File "Tensorflow\models\research\object_detection\model_main_tf2.py", line 106, in main model_lib_v2.train_loop( File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\model_lib_v2.py", line 541, in train_loop detection_model = MODEL_BUILD_UTIL_MAP['detection_model_fn_base']( File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 1249, in build return build_func(getattr(model_config, meta_architecture), is_training, File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 400, in _build_ssd_model _check_feature_extractor_exists(ssd_config.feature_extractor.type) File "E:\dd\TFODCourse\rg1\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 266, in _check_feature_extractor_exists raise ValueError('{} is not supported. See `model_builder.py` for features ' ValueError: is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow
> 
> plz help me to resolve this error.

Facing exactly the same problem with the "mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8" model. unable to find any answers.

my command: "python Tensorflow\models\research\object_detection\model_main_tf2.py --model_dir=Tensorflow\workspace\models\mask_rcnn --pipeline_config_path=Tensorflow\workspace\models\mask_rcnn\pipeline.config --num_train_steps=2000"

Any help is apreceated (my code workrs with the SSD mobilenet V2 320x320).

**Comment by ck12780** [comment]
![Screenshot 2024-01-11 211728](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/assets/155506569/b1a59d80-dbcc-4a89-99e1-610d15bad121)
Hi i am facing the same issues using pretrained model [Faster R-CNN Inception ResNet V2 640x640](http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_inception_resnet_v2_640x640_coco17_tpu-8.tar.gz) 
Using Google Colab
Tensorflow version:2.13.0
Python 3.10.12
