### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '(88, 100)'

### ISSUE THREAD

**Issue by PizzaRules668** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#522]
When I run the xml_to_cvs.py I get
`Traceback (most recent call last):
  File "xml_to_csv.py", line 36, in <module>
    main()
  File "xml_to_csv.py", line 31, in main
    xml_df = xml_to_csv(image_path)
  File "xml_to_csv.py", line 19, in xml_to_csv
    int(member[4][2].text),
ValueError: invalid literal for int() with base 10: '(88, 100)'`

**Comment by PizzaRules668** [comment]
Bounding box was outside of image
