### ISSUE TITLE
problem in generating tfrecords

### ISSUE THREAD

**Issue by SNitika** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#545]
(tf-gpu) C:\OD\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
2021-02-10 10:12:14.975067: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "generate_tfrecord.py", line 104, in <module>
    tf.app.run()
  File "C:\Users\DELL\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\DELL\Anaconda3\envs\tf-gpu\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\DELL\Anaconda3\envs\tf-gpu\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 95, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 50, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\DELL\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "C:\Users\DELL\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\OD\models\research\object_detection\images\train\1 : The system cannot find the file specified.
; No such file or directory

**Comment by Petros626** [comment]
i have the same issue....dont know what else i can do
