### ISSUE TITLE
No module named 'nets'

### ISSUE THREAD

**Issue by songkranandta** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#583]
(tensorflow_gpu_tar) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
C:\Users\Admin\anaconda3\envs\tensorflow_gpu_tar\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Admin\anaconda3\envs\tensorflow_gpu_tar\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
C:\Users\Admin\anaconda3\envs\tensorflow_gpu_tar\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)
2021-11-05 19:40:34.145466: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\Admin\anaconda3\envs\tensorflow_gpu_tar\lib\site-packages\object_detection\builders\model_builder.py", line 73, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\Users\Admin\anaconda3\envs\tensorflow_gpu_tar\lib\site-packages\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 30, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'

**Comment by prayagpawar** [comment]
I solved this by rebuilding protos go and check  /models/research/object_detection/protos check for file center_net_pb2.py check all files if protos are generated if not generate manually by code.
