### ISSUE TITLE
faster_rcnn_nas_coco ValueError

### ISSUE THREAD

**Issue by austinmw** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#61]
I've previously tried two models: `ssd_mobilenet_v1_coco_2017_11_17` and `faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28` which will both run. For faster rcnn to work I had to make a python3 `list(range())` fix found [here](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/issues/11). Now with everything else remaining the same I try to run `faster_rcnn_nas_coco_2018_01_28`, but get the error: 

> Traceback (most recent call last):
>   File "/home/awelch/training/train.py", line 184, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "/home/awelch/training/train.py", line 180, in main
>     graph_hook_fn=graph_rewriter_fn)
>   File "/tensorflow/models/research/object_detection/trainer.py", line 285, in train
>     clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
>   File "/tensorflow/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
>     outputs = model_fn(*args, **kwargs)
>   File "/tensorflow/models/research/object_detection/trainer.py", line 177, in _create_losses
>     train_config.use_multiclass_scores)
> ValueError: not enough values to unpack (expected 7, got 0)

Anybody know how to fix this or if I need another python 3 fix for this model?

**Comment by kolligowtham** [comment]
Hi ,
Struck with the same issue .....
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS, first_clone_scope)
training stops at this line 
Did u find any solution ??
working fine for other models
