### ISSUE TITLE
Error during Running the training

### ISSUE THREAD

**Issue by osama191** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#74]
Followed all the steps successfully. Getting this error while running the training.

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --
logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_in
ception_v2_pets.config
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\trainer.
py:260: create_global_step (from tensorflow.contrib.framework.python.ops.variabl
es) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.

INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\core\box
_predictor.py:407: calling reduce_mean (from tensorflow.python.ops.math_ops) wit
h keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\core\los
ses.py:317: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops
) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Traceback (most recent call last):
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\constant_op.py", line 235, in _constant_tensor_conversion_functi
on
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\tensor_util.py", line 441, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: range(0, 3) - got shape [3], but wa
nted [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\constant_op.py", line 235, in _constant_tensor_conversion_functi
on
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\tensor_util.py", line 441, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: range(0, 3) - got shape [3], but wa
nted [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\trainer.py", line 298, i
n train
    train_config.optimizer)
  File "C:\tensorflow1\models\research\object_detection\builders\optimizer_build
er.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "C:\tensorflow1\models\research\object_detection\builders\optimizer_build
er.py", line 109, in _create_learning_rate
    learning_rate_sequence, config.warmup)
  File "C:\tensorflow1\models\research\object_detection\utils\learning_schedules
.py", line 169, in manual_stepping
    [0] * num_boundaries))
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\ops\array_ops.py", line 2681, in where
    return gen_math_ops.select(condition=condition, x=x, y=y, name=name)
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\ops\gen_math_ops.py", line 7189, in select
    "Select", condition=condition, t=x, e=y, name=name)
  File "C:\Users\Osama\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\p
ython\framework\op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 't' to a tensor and failed. Error: Argument must be
 a dense tensor: range(0, 3) - got shape [3], but wanted [].

**Comment by 6monkeyrs** [comment]
Bump .. I got the same error running Anaconda w/tensorflow 1.8
