### ISSUE TITLE
When I run train.py, It always point to the wrong path：D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py

### ISSUE THREAD

**Issue by zhigangjun** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#84]
WARNING:tensorflow:From D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py:260: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
WARNING:tensorflow:From D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\core\box_predictor.py:407: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\core\losses.py:317: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

Traceback (most recent call last):
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1036, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 442, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: range(0, 3) - got shape [3], but wanted [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1036, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 442, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: range(0, 3) - got shape [3], but wanted [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py", line 298, in train
    train_config.optimizer)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\optimizer_builder.py", line 50, in build
    learning_rate = _create_learning_rate(config.learning_rate)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\optimizer_builder.py", line 109, in _create_learning_rate
    learning_rate_sequence, config.warmup)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\learning_schedules.py", line 169, in manual_stepping
    [0] * num_boundaries))
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2619, in where
    return gen_math_ops._select(condition=condition, x=x, y=y, name=name)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4503, in _select
    "Select", condition=condition, t=x, e=y, name=name)
  File "D:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 't' to a tensor and failed. Error: Argument must be a dense tensor: range(0, 3) - got shape [3], but wanted [].

when I run train.py ， It always point to the wrong pathD:\Anaconda3；I think he should point to the path“D:\tensorflow1\models\research\object_detection\trainer.py” .      And In the faster_rcnn_inception_v2_pets.config  I have change the path correctly~
Please help me...
I'll really appreciate you.~

**Comment by zhigangjun** [comment]
solved

**Comment by suravijayjilla** [comment]
hi,
Please give me the solution how to solve this error

**Comment by suravijayjilla** [comment]
hi,
Please give me the solution how to solve this error
