### ISSUE TITLE
Error in step 4 generating the training data

### ISSUE THREAD

**Issue by Elites2017** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#90]
Who can help me? Everything was working fine until I got to step 4. When I tried to generate the training data, i got this error.

(tensflow) C:\tensorflow1\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record                                                                                                                              Traceback (most recent call last):                                                                                                                      File "generate_tfrecord.py", line 110, in <module>                                                                                                      tf.app.run()                                                                                                                                        File "C:\Users\David-Up\Anaconda3\envs\tensflow\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run                                  _sys.exit(main(argv))                                                                                                                               File "generate_tfrecord.py", line 101, in main                                                                                                          tf_example = create_tf_example(group, path)                                                                                                         File "generate_tfrecord.py", line 90, in create_tf_example                                                                                              'image/object/class/label': dataset_util.int64_list_feature(classes),                                                                               File "C:\Users\David-Up\Anaconda3\envs\tensflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\dataset_util.py", line 26, in int64_list_feature                                                                                                                                      return tf.train.Feature(int64_list=tf.train.Int64List(value=value))                                                                               TypeError: None has type NoneType, but expected one of: int, long

Note: that i'm using the same project to detect cards, that means I don't change anything in the label map.

Thanks in advance for your help guys.

Regards,

**Comment by Shaiken** [comment]
hi, i need cpu mode, but i try a lot method, environment fail
i install gradation
1. python-3.5.4-amd64.exe from windows
2. Anaconda3-5.3.1-Windows-x86_64.exe from windows
3. create tensorflow1 dir to C:\
4. git tensorflow mode to C:\tensorfolw1
5. conda create -n tensorflow1 pip python=3.5
6. pip install --ignore-installed --upgrade tensorflow==1.10

other step just like author, but just set cmd => python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config... will fail
