### ISSUE TITLE
Error when I tried to train

### ISSUE THREAD

**Issue by anzy0621** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#91]
Hello, so I followed all the steps in this tutorial and just when I finally started to train. I got this error:

(tensorflow) C:\Users\Anusha\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_resnet_v2_atrous_coco.config
WARNING:tensorflow:From C:\Users\Anusha\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py:260: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Anusha\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\Anusha\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py", line 274, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\Users\Anusha\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 120, in get_next
    return dataset_util.make_initializable_iterator(
AttributeError: module 'object_detection.utils.dataset_util' has no attribute 'make_initializable_iterator'

(tensorflow) C:\Users\Anusha\models\research\object_detection>AttributeError: module 'object_detection.utils.dataset_util' has no attribute 'make_initializable_iterator'

**Comment by welder83** [comment]
Hello, I also have the same problem using the latest tensorflow/models.
Please help to check, Thanks!

**Comment by jacsmith21** [comment]
They changed the location. Use this:
```
from object_detection.builders import dataset_builder
...
dataset_builder.make_initializable_iterator(...)
```

**Comment by welder83** [comment]
@jacsmith21  Thanks, It's working!

1. add 'from object_detection.builders import dataset_builder'
2. change
    `return dataset_util.make_initializable_iterator(dataset_builder.build(config)).get_next()`
      to
    `return dataset_builder.make_initializable_iterator(dataset_builder.build(config)).get_next()`
