### ISSUE TITLE
Hello I got an error when I start training, new error TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)

### ISSUE THREAD

**Issue by Adibhatt95** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#99]
I ran this code: 

This was the error: TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)

 
(base) C:\Users\Aditya\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
C:\Users\Aditya\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From C:\Users\Aditya\models\research\object_detection\trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\Aditya\models\research\object_detection\trainer.py", line 228, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "C:\Users\Aditya\models\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "C:\Users\Aditya\models\research\object_detection\trainer.py", line 155, in _create_losses
    images = tf.concat(images, 0)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1112, in concat
    return identity(values[0], name=scope)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 79, in identity
    return gen_array_ops.identity(input, name=name)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3887, in identity
    "Identity", input=input, name=name)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 960, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 902, in _autopacking_helper
    elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)

PLease help I use tensorflow version 1.9 this should have worked.

**Comment by thak123** [comment]
The model expects float values and you are providing int values. if you check the xml to csv file it has xmin ymin .. etc on line 17-20 as int . Please try changing it to float and then try,

I think this should solve your issue.

**Comment by Adibhatt95** [comment]
@thak123  thanks for your input, I would have liked to try that but I realized that tensorflow/models repo I was using was of the latest version, which was the problem it seems, I just went back the exact commit that they used when creating this tutorial API, and it worked then and I am training successfully now. Thanks! I will close this.

**Comment by chuck881111** [comment]
Hi  Adibhatt95,
I met the same issue, how to solve it in your side?

**Comment by Adibhatt95** [comment]
@chuck881111 the issue was the I was using the wrong commit of tensorflow/models repo.
Use the exact same commit they used, there is a link to it in the first paragraph of the tutorial

**Comment by chuck881111** [comment]
@Adibhatt95 after I used TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10 repo, the error is still the same.
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/scratch.chuckc_gp108/python/imagenet/tt/models/research/object_detection/trainer.py", line 228, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/scratch.chuckc_gp108/python/imagenet/tt/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/scratch.chuckc_gp108/python/imagenet/tt/models/research/object_detection/trainer.py", line 155, in _create_losses
    images = tf.concat(images, 0)
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1063, in concat
    return identity(values[0], name=scope)
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1400, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
    raise err
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 937, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/home/scratch.chuckc_gp108/ML/anaconda/min/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 879, in _autopacking_helper
    "%s to %s (Tensor is: %r)" % (elem.dtype, dtype, elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)

**Comment by Adibhatt95** [comment]
@chuck881111  I'm talking about the tensorflow/models repo, that repo needs to be in the exact commit that the TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10  repo used to make it work

**Comment by chuck881111** [comment]
@Adibhatt95 
actually I have used below model,could you help to double check it? thanks a lot!
https://github.com/tensorflow/models/tree/079d67d9a0b3407e8d074a200780f3835413ef99

**Comment by Adibhatt95** [comment]
@chuck881111  yes https://github.com/tensorflow/models/tree/079d67d9a0b3407e8d074a200780f3835413ef99 
this is the correct repo, seems you used it, so I am not sure about why this is happening, I used tensorflow 1.5, python 3.6.4 and cuda 9.0 and cuDNN 7.0.5

**Comment by Adibhatt95** [comment]
Maybe that will help ^ @chuck881111

**Comment by danielshaving** [comment]
> I ran this code:
> 
> This was the error: TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)
> 
> (base) C:\Users\Aditya\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
> C:\Users\Aditya\Anaconda3\lib\site-packages\h5py__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
> from ._conv import register_converters as _register_converters
> WARNING:tensorflow:From C:\Users\Aditya\models\research\object_detection\trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please switch to tf.train.create_global_step
> Traceback (most recent call last):
> File "train.py", line 163, in 
> tf.app.run()
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
> _sys.exit(main(argv))
> File "train.py", line 159, in main
> worker_job_name, is_chief, FLAGS.train_dir)
> File "C:\Users\Aditya\models\research\object_detection\trainer.py", line 228, in train
> clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
> File "C:\Users\Aditya\models\research\slim\deployment\model_deploy.py", line 193, in create_clones
> outputs = model_fn(*args, **kwargs)
> File "C:\Users\Aditya\models\research\object_detection\trainer.py", line 155, in _create_losses
> images = tf.concat(images, 0)
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1112, in concat
> return identity(values[0], name=scope)
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 79, in identity
> return gen_array_ops.identity(input, name=name)
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3887, in identity
> "Identity", input=input, name=name)
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
> raise err
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
> preferred_dtype=default_dtype)
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1107, in internal_convert_to_tensor
> ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 960, in _autopacking_conversion_function
> return _autopacking_helper(v, inferred_dtype, name or "packed")
> File "C:\Users\Aditya\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 902, in _autopacking_helper
> elem))
> TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)
> 
> PLease help I use tensorflow version 1.9 this should have worked.

did you solved this ?

**Comment by siddas27** [comment]
@chuck881111 @danielshaving  did you solve?
